module PublicHolidays
  module Countries
    class Italy < CountryPublicHolidays
      def initialize
        @public_holidays = [
          PublicHoliday.new(start_date: Date.new(2011, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2011, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2011, 3, 17), local_name: "150° anniversario della proclamazione dell'Unita' d'Italia", english_name: "150th anniversary of the unification of Italy"),
          PublicHoliday.new(start_date: Date.new(2011, 4, 24), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2011, 4, 25), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2011, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2011, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2011, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2011, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2011, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2011, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2011, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2011, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2012, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2012, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2012, 4, 8), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2012, 4, 9), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2012, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2012, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2012, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2012, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2012, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2012, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2012, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2012, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2013, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2013, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2013, 3, 31), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2013, 4, 1), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2013, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2013, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2013, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2013, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2013, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2013, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2013, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2013, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2014, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2014, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2014, 4, 20), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2014, 4, 21), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2014, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2014, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2014, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2014, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2014, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2014, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2014, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2014, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2015, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2015, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2015, 4, 5), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2015, 4, 6), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2015, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2015, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2015, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2015, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2015, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2015, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2015, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2015, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2016, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2016, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2016, 3, 27), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2016, 3, 28), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2016, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2016, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2016, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2016, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2016, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2016, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2016, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2016, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2017, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2017, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2017, 4, 16), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2017, 4, 17), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2017, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2017, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2017, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2017, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2017, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2017, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2017, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2017, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2018, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2018, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2018, 4, 1), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2018, 4, 2), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2018, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2018, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2018, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2018, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2018, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2018, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2018, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2018, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2019, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2019, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2019, 4, 21), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2019, 4, 22), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2019, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2019, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2019, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2019, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2019, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2019, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2019, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2019, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2020, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2020, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2020, 4, 12), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2020, 4, 13), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2020, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2020, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2020, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2020, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2020, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2020, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2020, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2020, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2021, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2021, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2021, 4, 4), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2021, 4, 5), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2021, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2021, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2021, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2021, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2021, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2021, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2021, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2021, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2022, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2022, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2022, 4, 17), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2022, 4, 18), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2022, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2022, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2022, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2022, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2022, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2022, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2022, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2022, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2023, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2023, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2023, 4, 9), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2023, 4, 10), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2023, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2023, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2023, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2023, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2023, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2023, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2023, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2023, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2024, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2024, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2024, 3, 31), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2024, 4, 1), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2024, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2024, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2024, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2024, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2024, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2024, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2024, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2024, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2025, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2025, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2025, 4, 20), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2025, 4, 21), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2025, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2025, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2025, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2025, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2025, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2025, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2025, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2025, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2026, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2026, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2026, 4, 5), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2026, 4, 6), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2026, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2026, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2026, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2026, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2026, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2026, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2026, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2026, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2027, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2027, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2027, 3, 28), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2027, 3, 29), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2027, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2027, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2027, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2027, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2027, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2027, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2027, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2027, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2028, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2028, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2028, 4, 16), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2028, 4, 17), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2028, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2028, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2028, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2028, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2028, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2028, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2028, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2028, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2029, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2029, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2029, 4, 1), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2029, 4, 2), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2029, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2029, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2029, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2029, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2029, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2029, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2029, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2029, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2030, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2030, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2030, 4, 21), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2030, 4, 22), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2030, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2030, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2030, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2030, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2030, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2030, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2030, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2030, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2031, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2031, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2031, 4, 13), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2031, 4, 14), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2031, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2031, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2031, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2031, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2031, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2031, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2031, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2031, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2032, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2032, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2032, 3, 28), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2032, 3, 29), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2032, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2032, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2032, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2032, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2032, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2032, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2032, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2032, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2033, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2033, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2033, 4, 17), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2033, 4, 18), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2033, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2033, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2033, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2033, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2033, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2033, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2033, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2033, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2034, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2034, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2034, 4, 9), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2034, 4, 10), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2034, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2034, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2034, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2034, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2034, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2034, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2034, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2034, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2035, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2035, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2035, 3, 25), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2035, 3, 26), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2035, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2035, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2035, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2035, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2035, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2035, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2035, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2035, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2036, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2036, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2036, 4, 13), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2036, 4, 14), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2036, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2036, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2036, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2036, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2036, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2036, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2036, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2036, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2037, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2037, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2037, 4, 5), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2037, 4, 6), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2037, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2037, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2037, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2037, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2037, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2037, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2037, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2037, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2038, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2038, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2038, 4, 25), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2038, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2038, 4, 26), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2038, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2038, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2038, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2038, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2038, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2038, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2038, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2039, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2039, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2039, 4, 10), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2039, 4, 11), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2039, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2039, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2039, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2039, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2039, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2039, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2039, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2039, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
          PublicHoliday.new(start_date: Date.new(2040, 1, 1), local_name: "Capodanno", english_name: "New Year's Day"),
          PublicHoliday.new(start_date: Date.new(2040, 1, 6), local_name: "Epifania", english_name: "Epiphany"),
          PublicHoliday.new(start_date: Date.new(2040, 4, 1), local_name: "Pasqua", english_name: "Easter Sunday"),
          PublicHoliday.new(start_date: Date.new(2040, 4, 2), local_name: "Lunedì dell'Angelo, Pasquetta", english_name: "Easter Monday"),
          PublicHoliday.new(start_date: Date.new(2040, 4, 25), local_name: "Anniversario della Liberazione", english_name: "Anniversary of Liberation"),
          PublicHoliday.new(start_date: Date.new(2040, 5, 1), local_name: "Festa del Lavoro (Festa dei Lavoratori)", english_name: "Labour Day"),
          PublicHoliday.new(start_date: Date.new(2040, 6, 2), local_name: "Festa della Repubblica", english_name: "Republic Day"),
          PublicHoliday.new(start_date: Date.new(2040, 8, 15), local_name: "Ferragosto and Assunzione", english_name: "Assumption of Mary"),
          PublicHoliday.new(start_date: Date.new(2040, 11, 1), local_name: "Tutti i santi (Ognissanti)", english_name: "All Saints' Day"),
          PublicHoliday.new(start_date: Date.new(2040, 12, 8), local_name: "Immacolata Concezione", english_name: "Immaculate Conception Day"),
          PublicHoliday.new(start_date: Date.new(2040, 12, 25), local_name: "Natale", english_name: "Christmas Day"),
          PublicHoliday.new(start_date: Date.new(2040, 12, 26), local_name: "Santo Stefano", english_name: "St Stephen's Day"),
        ]
      end
    end
  end
end
