module NationalHolidays
  module Countries
    class Belgium < CountryNationalHolidays

      attr_reader :brussels

      def default
        self.brussels
      end

      def initialize
        @regions = [ 'Brussels' ]

        @brussels = [
          NationalHoliday.new(Date.new(2011, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 4, 24), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2011, 6, 2), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2011, 6, 12), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2011, 6, 13), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2011, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2011, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2011, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2011, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2011, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 4, 8), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2012, 5, 17), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2012, 5, 27), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2012, 5, 28), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2012, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2012, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2012, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2012, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 3, 31), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2013, 5, 9), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2013, 5, 19), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2013, 5, 20), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2013, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2013, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2013, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2013, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2014, 5, 29), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2014, 6, 8), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2014, 6, 9), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2014, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2014, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2014, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2014, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 4, 5), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2015, 5, 14), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2015, 5, 24), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2015, 5, 25), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2015, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2015, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2015, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2015, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2016, 5, 5), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2016, 5, 15), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2016, 5, 16), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2016, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2016, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2016, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2016, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2017, 5, 25), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2017, 6, 4), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2017, 6, 5), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2017, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2017, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2017, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2017, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2018, 5, 10), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2018, 5, 20), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2018, 5, 21), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2018, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2018, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2018, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2018, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2019, 5, 30), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2019, 6, 9), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2019, 6, 10), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2019, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2019, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2019, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2019, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2020, 5, 21), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2020, 5, 31), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2020, 6, 1), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2020, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2020, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2020, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2020, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2021, 5, 13), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2021, 5, 23), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2021, 5, 24), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2021, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2021, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2021, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2021, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2022, 5, 26), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2022, 6, 5), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2022, 6, 6), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2022, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2022, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2022, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2022, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2023, 5, 18), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2023, 5, 28), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2023, 5, 29), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2023, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2023, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2023, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2023, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2024, 5, 9), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2024, 5, 19), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2024, 5, 20), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2024, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2024, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2024, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2024, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2025, 5, 29), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2025, 6, 8), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2025, 6, 9), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2025, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2025, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2025, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2025, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2026, 5, 14), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2026, 5, 24), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2026, 5, 25), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2026, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2026, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2026, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2026, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2027, 5, 6), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2027, 5, 16), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2027, 5, 17), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2027, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2027, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2027, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2027, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2028, 5, 25), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2028, 6, 4), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2028, 6, 5), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2028, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2028, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2028, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2028, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2029, 5, 10), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2029, 5, 20), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2029, 5, 21), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2029, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2029, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2029, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2029, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2030, 5, 30), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2030, 6, 9), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2030, 6, 10), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2030, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2030, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2030, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2030, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2031, 5, 22), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2031, 6, 1), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2031, 6, 2), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2031, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2031, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2031, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2031, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2032, 5, 6), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2032, 5, 16), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2032, 5, 17), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2032, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2032, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2032, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2032, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2033, 5, 26), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2033, 6, 5), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2033, 6, 6), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2033, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2033, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2033, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2033, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2034, 5, 18), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2034, 5, 28), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2034, 5, 29), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2034, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2034, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2034, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2034, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2035, 5, 3), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2035, 5, 13), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2035, 5, 14), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2035, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2035, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2035, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2035, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2036, 5, 22), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2036, 6, 1), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2036, 6, 2), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2036, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2036, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2036, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2036, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2037, 5, 14), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2037, 5, 24), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2037, 5, 25), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2037, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2037, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2037, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2037, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2038, 6, 3), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2038, 6, 13), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2038, 6, 14), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2038, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2038, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2038, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2038, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2039, 5, 19), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2039, 5, 29), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2039, 5, 30), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2039, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2039, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2039, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2039, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Nieuwjaar / Nouvel An / Neujahr", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Pasen / Pâques / Ostern", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Paasmaandag / Lundi de Pâques / Ostermontag", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Dag van de arbeid / Fête du Travail / Tag der Arbeit", "Labour Day"),
          NationalHoliday.new(Date.new(2040, 5, 10), "Onze Lieve Heer hemelvaart / Ascension / Christi Himmelfahrt", "Ascension Day"),
          NationalHoliday.new(Date.new(2040, 5, 20), "Pinksteren / Pentecôte / Pfingsten", "Whit Sunday"),
          NationalHoliday.new(Date.new(2040, 5, 21), "Pinkstermaandag / Lundi de Pentecôte / Pfingstmontag", "Whit Monday"),
          NationalHoliday.new(Date.new(2040, 7, 21), "Nationale feestdag / Fête nationale / Nationalfeiertag", "National holiday"),
          NationalHoliday.new(Date.new(2040, 8, 15), "Onze Lieve Vrouw hemelvaart / Assomption / Mariä Himmelfahrt", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2040, 11, 1), "Allerheiligen / Toussaint / Allerheiligen", "All Saints' Day"),
          NationalHoliday.new(Date.new(2040, 11, 11), "Wapenstilstand (Belgische feestdag) / Jour de l'armistice / Waffenstillstand", "Armistice Day"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Kerstmis / Noël / Weihnachten", "Christmas Day")
        ]
      end
    end
  end
end
