module NationalHolidays
  module Countries
    class Brazil < CountryNationalHolidays

      attr_reader :rio_de_janeiro

      def default
        self.rio_de_janeiro
      end

      def initialize
        @regions = [ 'Rio de Janeiro' ]

        @rio_de_janeiro = [
          NationalHoliday.new(Date.new(2016, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 2, 8), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2016, 2, 9), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2016, 2, 10), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2016, 3, 25), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2016, 5, 26), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2016, 8, 5), "Feriado Municipal", "Municipal Public Holiday"),
          NationalHoliday.new(Date.new(2016, 8, 18), "Feriado Municipal", "Municipal Public Holiday"),
          NationalHoliday.new(Date.new(2016, 8, 22), "Feriado Municipal", "Municipal Public Holiday"),
          NationalHoliday.new(Date.new(2016, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2016, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2016, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2016, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2016, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2016, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 2, 27), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2017, 2, 28), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2017, 3, 1), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2017, 6, 15), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2017, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2017, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2017, 10, 27), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2017, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2017, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2017, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 2, 12), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2018, 2, 13), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2018, 2, 14), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2018, 3, 30), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2018, 5, 31), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2018, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2018, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2018, 10, 29), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2018, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2018, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2018, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 3, 4), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2019, 3, 5), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2019, 3, 6), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2019, 4, 19), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2019, 6, 20), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2019, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2019, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2019, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2019, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2019, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2019, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 2, 24), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2020, 2, 25), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2020, 2, 26), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2020, 4, 10), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2020, 6, 11), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2020, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2020, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2020, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2020, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2020, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2020, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 2, 15), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2021, 2, 16), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2021, 2, 17), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2021, 4, 2), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2021, 6, 3), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2021, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2021, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2021, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2021, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2021, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2021, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 2, 28), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2022, 3, 1), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2022, 3, 2), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2022, 4, 15), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2022, 6, 16), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2022, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2022, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2022, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2022, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2022, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2022, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 2, 20), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2023, 2, 21), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2023, 2, 22), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2023, 4, 7), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2023, 6, 8), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2023, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2023, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2023, 10, 27), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2023, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2023, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2023, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 2, 12), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2024, 2, 13), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2024, 2, 14), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2024, 3, 29), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2024, 5, 30), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2024, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2024, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2024, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2024, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2024, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2024, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 3, 3), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2025, 3, 4), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2025, 3, 5), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2025, 6, 19), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2025, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2025, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2025, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2025, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2025, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2025, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 2, 16), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2026, 2, 17), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2026, 2, 18), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2026, 4, 3), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2026, 6, 4), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2026, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2026, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2026, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2026, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2026, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2026, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 2, 8), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2027, 2, 9), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2027, 2, 10), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2027, 3, 26), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2027, 5, 27), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2027, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2027, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2027, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2027, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2027, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2027, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 2, 28), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2028, 2, 29), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2028, 3, 1), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2028, 6, 15), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2028, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2028, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2028, 10, 27), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2028, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2028, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2028, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 2, 12), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2029, 2, 13), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2029, 2, 14), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2029, 3, 30), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2029, 5, 31), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2029, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2029, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2029, 10, 29), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2029, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2029, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2029, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 3, 4), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2030, 3, 5), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2030, 3, 6), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2030, 4, 19), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2030, 6, 20), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2030, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2030, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2030, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2030, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2030, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2030, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 2, 24), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2031, 2, 25), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2031, 2, 26), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2031, 6, 12), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2031, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2031, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2031, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2031, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2031, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2031, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 2, 9), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2032, 2, 10), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2032, 2, 11), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2032, 3, 26), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2032, 5, 27), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2032, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2032, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2032, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2032, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2032, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2032, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 2, 28), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2033, 3, 1), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2033, 3, 2), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2033, 4, 15), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2033, 6, 16), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2033, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2033, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2033, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2033, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2033, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2033, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 2, 20), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2034, 2, 21), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2034, 2, 22), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2034, 6, 8), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2034, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2034, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2034, 10, 27), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2034, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2034, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2034, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 2, 5), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2035, 2, 6), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2035, 2, 7), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2035, 3, 23), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2035, 5, 24), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2035, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2035, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2035, 10, 29), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2035, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2035, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2035, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 2, 25), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2036, 2, 26), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2036, 2, 27), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2036, 4, 11), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2036, 6, 12), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2036, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2036, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2036, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2036, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2036, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2036, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 2, 16), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2037, 2, 17), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2037, 2, 18), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2037, 6, 4), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2037, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2037, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2037, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2037, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2037, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2037, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 3, 8), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2038, 3, 9), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2038, 3, 10), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2038, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2038, 6, 24), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2038, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2038, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2038, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2038, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2038, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2038, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 2, 21), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2039, 2, 22), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2039, 2, 23), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2039, 4, 8), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2039, 6, 9), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2039, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2039, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2039, 10, 28), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2039, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2039, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2039, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Natal", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Ano Novo / Confraternizaçao Universal", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 2, 13), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2040, 2, 14), "Carnaval", "Carnival"),
          NationalHoliday.new(Date.new(2040, 2, 15), "Quarta-feira de Cinzas", "Ash Wednesday"),
          NationalHoliday.new(Date.new(2040, 3, 30), "Paixao de Cristo", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 21), "Dia de Tiradentes", "Tiradentes' Day"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Dia do Trabalhador (Dia do Trabalho)", "Labour Day"),
          NationalHoliday.new(Date.new(2040, 5, 31), "Corpo de Deus", "Corpus Christi"),
          NationalHoliday.new(Date.new(2040, 9, 7), "Dia da Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2040, 10, 12), "Nossa Senhora Aparecida", "Lady of Aparecida Day"),
          NationalHoliday.new(Date.new(2040, 10, 29), "Dia do Servidor Público", "Civil Servants' Day"),
          NationalHoliday.new(Date.new(2040, 11, 2), "Dia de Finados", "All Souls' Day"),
          NationalHoliday.new(Date.new(2040, 11, 15), "Proclamaçao da República", "Republic Day"),
          NationalHoliday.new(Date.new(2040, 11, 20), "Black Consciousness Day", "Dia da Consciencia Negra"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Natal", "Christmas Day")
        ]
      end
    end
  end
end
