module NationalHolidays
  module Countries
    class China < CountryNationalHolidays

      attr_reader :beijing_municipality

      def default
        self.beijing_municipality
      end

      def initialize
        @regions = [ 'Beijing Municipality' ]

        @beijing_municipality = [
          NationalHoliday.new(Date.new(2013, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2013, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2013, 2, 9), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2013, 2, 10), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2013, 2, 11), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2013, 2, 12), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2013, 2, 13), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2013, 2, 14), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2013, 2, 15), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2013, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2013, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2013, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2013, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2013, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2013, 6, 10), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2013, 6, 11), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2013, 6, 12), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2013, 9, 19), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2013, 9, 20), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2013, 9, 21), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2013, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2013, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2013, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2013, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2013, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2013, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2013, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2014, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 1, 31), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2014, 2, 1), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2014, 2, 2), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2014, 2, 3), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2014, 2, 4), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2014, 2, 5), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2014, 2, 6), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2014, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2014, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2014, 4, 7), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2014, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2014, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2014, 5, 31), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2014, 6, 1), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2014, 6, 2), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2014, 9, 6), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2014, 9, 7), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2014, 9, 8), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2014, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2014, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2014, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2014, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2014, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2014, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2014, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2015, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2015, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2015, 2, 18), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2015, 2, 19), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2015, 2, 20), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2015, 2, 21), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2015, 2, 22), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2015, 2, 23), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2015, 2, 24), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2015, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2015, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2015, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2015, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2015, 6, 20), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2015, 6, 21), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2015, 6, 22), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2015, 9, 3), "抗战胜利70周年纪念活动", "70 Year Anniversary of the Chinese people’s Resistance against Japan and the Global Victory over Fascism"),
          NationalHoliday.new(Date.new(2015, 9, 4), "抗战胜利70周年纪念活动", "70 Year Anniversary of the Chinese people’s Resistance against Japan and the Global Victory over Fascism"),
          NationalHoliday.new(Date.new(2015, 9, 5), "抗战胜利70周年纪念活动", "70 Year Anniversary of the Chinese people’s Resistance against Japan and the Global Victory over Fascism"),
          NationalHoliday.new(Date.new(2015, 9, 27), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2015, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2015, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2015, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2015, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2015, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2015, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2015, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2016, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2016, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2016, 2, 7), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2016, 2, 8), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2016, 2, 9), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2016, 2, 10), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2016, 2, 11), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2016, 2, 12), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2016, 2, 13), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2016, 4, 2), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2016, 4, 3), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2016, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2016, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2016, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2016, 6, 9), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2016, 6, 10), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2016, 6, 11), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2016, 9, 15), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2016, 9, 16), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2016, 9, 17), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2016, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2016, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2016, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2016, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2016, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2016, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2016, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 27), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2017, 1, 28), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2017, 1, 29), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2017, 1, 30), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2017, 1, 31), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2017, 2, 1), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2017, 2, 2), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2017, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2017, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2017, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2017, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2017, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2017, 5, 28), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2017, 5, 29), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2017, 5, 30), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2017, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2017, 10, 2), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2017, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2017, 10, 3), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2017, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2017, 10, 4), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2017, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2017, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2017, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2017, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2018, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2018, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2018, 2, 15), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2018, 2, 16), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2018, 2, 17), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2018, 2, 18), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2018, 2, 19), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2018, 2, 20), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2018, 2, 21), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2018, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2018, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2018, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2018, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2018, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2018, 6, 16), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2018, 6, 17), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2018, 6, 18), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2018, 9, 22), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2018, 9, 23), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2018, 9, 24), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2018, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2018, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2018, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2018, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2018, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2018, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2018, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2019, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2019, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2019, 2, 4), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2019, 2, 5), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2019, 2, 6), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2019, 2, 7), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2019, 2, 8), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2019, 2, 9), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2019, 2, 10), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2019, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2019, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2019, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2019, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2019, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2019, 6, 7), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2019, 6, 8), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2019, 6, 9), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2019, 9, 13), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2019, 9, 14), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2019, 9, 15), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2019, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2019, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2019, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2019, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2019, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2019, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2019, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2020, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2020, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2020, 1, 24), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2020, 1, 25), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2020, 1, 26), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2020, 1, 27), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2020, 1, 28), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2020, 1, 29), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2020, 1, 30), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2020, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2020, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2020, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2020, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2020, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2020, 6, 25), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2020, 6, 26), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2020, 6, 27), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2020, 10, 1), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2020, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2020, 10, 2), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2020, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2020, 10, 3), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2020, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2020, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2020, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2020, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2020, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2021, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2021, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2021, 2, 11), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2021, 2, 12), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2021, 2, 13), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2021, 2, 14), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2021, 2, 15), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2021, 2, 16), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2021, 2, 17), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2021, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2021, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2021, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2021, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2021, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2021, 6, 12), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2021, 6, 13), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2021, 6, 14), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2021, 9, 19), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2021, 9, 20), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2021, 9, 21), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2021, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2021, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2021, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2021, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2021, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2021, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2021, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 31), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2022, 2, 1), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2022, 2, 2), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2022, 2, 3), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2022, 2, 4), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2022, 2, 5), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2022, 2, 6), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2022, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2022, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2022, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2022, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2022, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2022, 6, 3), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2022, 6, 4), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2022, 6, 5), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2022, 9, 10), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2022, 9, 11), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2022, 9, 12), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2022, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2022, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2022, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2022, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2022, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2022, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2022, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 21), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2023, 1, 22), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2023, 1, 23), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2023, 1, 24), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2023, 1, 25), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2023, 1, 26), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2023, 1, 27), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2023, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2023, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2023, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2023, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2023, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2023, 6, 22), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2023, 6, 23), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2023, 6, 24), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2023, 9, 29), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2023, 9, 30), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2023, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2023, 10, 1), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2023, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2023, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2023, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2023, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2023, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2023, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2024, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2024, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2024, 2, 9), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2024, 2, 10), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2024, 2, 11), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2024, 2, 12), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2024, 2, 13), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2024, 2, 14), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2024, 2, 15), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2024, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2024, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2024, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2024, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2024, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2024, 6, 8), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2024, 6, 9), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2024, 6, 10), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2024, 9, 15), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2024, 9, 16), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2024, 9, 17), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2024, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2024, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2024, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2024, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2024, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2024, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2024, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2025, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2025, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2025, 1, 28), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2025, 1, 29), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2025, 1, 30), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2025, 1, 31), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2025, 2, 1), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2025, 2, 2), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2025, 2, 3), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2025, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2025, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2025, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2025, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2025, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2025, 5, 31), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2025, 6, 1), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2025, 6, 2), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2025, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2025, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2025, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2025, 10, 4), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2025, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2025, 10, 5), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2025, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2025, 10, 6), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2025, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2025, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2026, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2026, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2026, 2, 16), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2026, 2, 17), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2026, 2, 18), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2026, 2, 19), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2026, 2, 20), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2026, 2, 21), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2026, 2, 22), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2026, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2026, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2026, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2026, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2026, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2026, 6, 19), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2026, 6, 20), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2026, 6, 21), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2026, 9, 25), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2026, 9, 26), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2026, 9, 27), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2026, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2026, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2026, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2026, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2026, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2026, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2026, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2027, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2027, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2027, 2, 5), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2027, 2, 6), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2027, 2, 7), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2027, 2, 8), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2027, 2, 9), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2027, 2, 10), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2027, 2, 11), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2027, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2027, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2027, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2027, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2027, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2027, 6, 7), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2027, 6, 8), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2027, 6, 9), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2027, 9, 13), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2027, 9, 14), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2027, 9, 15), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2027, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2027, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2027, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2027, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2027, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2027, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2027, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 25), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2028, 1, 26), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2028, 1, 27), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2028, 1, 28), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2028, 1, 29), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2028, 1, 30), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2028, 1, 31), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2028, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2028, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2028, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2028, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2028, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2028, 5, 27), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2028, 5, 28), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2028, 5, 29), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2028, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2028, 10, 1), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2028, 10, 2), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2028, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2028, 10, 3), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2028, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2028, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2028, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2028, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2028, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2029, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2029, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2029, 2, 12), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2029, 2, 13), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2029, 2, 14), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2029, 2, 15), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2029, 2, 16), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2029, 2, 17), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2029, 2, 18), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2029, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2029, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2029, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2029, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2029, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2029, 6, 16), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2029, 6, 17), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2029, 6, 18), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2029, 9, 22), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2029, 9, 23), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2029, 9, 24), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2029, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2029, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2029, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2029, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2029, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2029, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2029, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2030, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2030, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2030, 2, 2), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2030, 2, 3), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2030, 2, 4), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2030, 2, 5), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2030, 2, 6), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2030, 2, 7), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2030, 2, 8), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2030, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2030, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2030, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2030, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2030, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2030, 6, 3), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2030, 6, 4), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2030, 6, 5), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2030, 9, 12), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2030, 9, 13), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2030, 9, 14), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2030, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2030, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2030, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2030, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2030, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2030, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2030, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2031, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2031, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2031, 1, 22), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2031, 1, 23), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2031, 1, 24), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2031, 1, 25), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2031, 1, 26), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2031, 1, 27), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2031, 1, 28), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2031, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2031, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2031, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2031, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2031, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2031, 6, 22), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2031, 6, 23), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2031, 6, 24), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2031, 9, 29), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2031, 9, 30), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2031, 10, 1), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2031, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2031, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2031, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2031, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2031, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2031, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2031, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2032, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2032, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2032, 2, 10), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2032, 2, 11), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2032, 2, 12), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2032, 2, 13), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2032, 2, 14), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2032, 2, 15), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2032, 2, 16), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2032, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2032, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2032, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2032, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2032, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2032, 6, 12), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2032, 6, 13), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2032, 6, 14), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2032, 9, 18), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2032, 9, 19), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2032, 9, 20), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2032, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2032, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2032, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2032, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2032, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2032, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2032, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 30), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2033, 1, 31), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2033, 2, 1), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2033, 2, 2), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2033, 2, 3), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2033, 2, 4), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2033, 2, 5), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2033, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2033, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2033, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2033, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2033, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2033, 5, 30), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2033, 5, 31), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2033, 6, 1), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2033, 9, 8), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2033, 9, 9), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2033, 9, 10), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2033, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2033, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2033, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2033, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2033, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2033, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2033, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2034, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2034, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2034, 2, 18), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2034, 2, 19), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2034, 2, 20), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2034, 2, 21), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2034, 2, 22), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2034, 2, 23), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2034, 2, 24), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2034, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2034, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2034, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2034, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2034, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2034, 6, 18), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2034, 6, 19), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2034, 6, 20), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2034, 9, 25), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2034, 9, 26), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2034, 9, 27), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2034, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2034, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2034, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2034, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2034, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2034, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2034, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2035, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2035, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2035, 2, 7), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2035, 2, 8), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2035, 2, 9), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2035, 2, 10), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2035, 2, 11), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2035, 2, 12), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2035, 2, 13), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2035, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2035, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2035, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2035, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2035, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2035, 6, 9), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2035, 6, 10), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2035, 6, 11), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2035, 9, 15), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2035, 9, 16), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2035, 9, 17), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2035, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2035, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2035, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2035, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2035, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2035, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2035, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 27), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2036, 1, 28), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2036, 1, 29), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2036, 1, 30), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2036, 1, 31), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2036, 2, 1), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2036, 2, 2), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2036, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2036, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2036, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2036, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2036, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2036, 5, 30), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2036, 5, 31), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2036, 6, 1), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2036, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2036, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2036, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2036, 10, 4), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2036, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2036, 10, 5), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2036, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2036, 10, 6), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2036, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2036, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2037, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2037, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2037, 2, 14), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2037, 2, 15), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2037, 2, 16), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2037, 2, 17), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2037, 2, 18), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2037, 2, 19), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2037, 2, 20), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2037, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2037, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2037, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2037, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2037, 6, 18), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2037, 6, 19), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2037, 6, 20), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2037, 9, 24), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2037, 9, 25), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2037, 9, 26), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2037, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2037, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2037, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2037, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2037, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2037, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2037, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2038, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2038, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2038, 2, 3), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2038, 2, 4), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2038, 2, 5), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2038, 2, 6), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2038, 2, 7), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2038, 2, 8), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2038, 2, 9), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2038, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2038, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2038, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2038, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2038, 5, 3), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2038, 6, 5), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2038, 6, 6), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2038, 6, 7), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2038, 9, 11), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2038, 9, 12), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2038, 9, 13), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2038, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2038, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2038, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2038, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2038, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2038, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2038, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 23), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2039, 1, 24), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2039, 1, 25), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2039, 1, 26), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2039, 1, 27), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2039, 1, 28), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2039, 1, 29), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2039, 4, 4), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2039, 4, 5), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2039, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2039, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2039, 5, 2), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2039, 5, 27), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2039, 5, 28), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2039, 5, 29), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2039, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2039, 10, 1), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2039, 10, 2), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2039, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2039, 10, 3), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2039, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2039, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2039, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2039, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2039, 10, 7), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2040, 1, 1), "元旦", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 1, 2), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2040, 1, 3), "元旦", "New Year Holiday"),
          NationalHoliday.new(Date.new(2040, 2, 11), "春节", "Spring Festival (Chinese New Year's Eve)"),
          NationalHoliday.new(Date.new(2040, 2, 12), "春节", "Spring Festival (Chinese New Year)"),
          NationalHoliday.new(Date.new(2040, 2, 13), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2040, 2, 14), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2040, 2, 15), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2040, 2, 16), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2040, 2, 17), "春节", "Spring Festival"),
          NationalHoliday.new(Date.new(2040, 4, 4), "清明节", "Tomb Sweeping Day"),
          NationalHoliday.new(Date.new(2040, 4, 5), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2040, 4, 6), "清明节", "Tomb Sweeping Day Holiday"),
          NationalHoliday.new(Date.new(2040, 4, 29), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2040, 4, 30), "劳动节", "Labor Day Holiday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "劳动节", "Labor Day"),
          NationalHoliday.new(Date.new(2040, 6, 14), "端午节", "Dragon Boat Festival"),
          NationalHoliday.new(Date.new(2040, 6, 15), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2040, 6, 16), "端午节", "Dragon Boat Festival Holiday"),
          NationalHoliday.new(Date.new(2040, 9, 20), "中秋节", "Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2040, 9, 21), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2040, 9, 22), "中秋节", "Mid-Autumn Festival Holiday"),
          NationalHoliday.new(Date.new(2040, 10, 1), "国庆节", "National Day"),
          NationalHoliday.new(Date.new(2040, 10, 2), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2040, 10, 3), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2040, 10, 4), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2040, 10, 5), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2040, 10, 6), "国庆节", "National Day Holiday"),
          NationalHoliday.new(Date.new(2040, 10, 7), "国庆节", "National Day Holiday")
        ]
      end
    end
  end
end
