module NationalHolidays
  module Countries
    class Colombia < CountryNationalHolidays

      attr_reader :bbuenos_aires

      def default
        self.bbuenos_aires
      end

      def initialize
        @regions = [ 'Buenos Aires' ]

        @buenos_aires = [
          NationalHoliday.new(Date.new(2016, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 1, 11), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2016, 3, 20), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2016, 3, 21), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2016, 3, 24), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2016, 3, 25), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2016, 5, 9), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2016, 5, 30), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2016, 6, 6), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2016, 7, 4), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2016, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2016, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2016, 8, 15), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2016, 10, 17), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2016, 11, 7), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2016, 11, 14), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2016, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 9), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2017, 3, 20), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2017, 4, 9), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 13), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2017, 5, 29), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2017, 6, 19), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2017, 6, 26), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2017, 7, 3), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2017, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2017, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2017, 8, 21), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2017, 10, 16), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2017, 11, 6), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2017, 11, 13), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2017, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 1, 8), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2018, 3, 19), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2018, 3, 25), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2018, 3, 29), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2018, 3, 30), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2018, 5, 14), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2018, 6, 4), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2018, 6, 11), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2018, 7, 2), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2018, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2018, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2018, 8, 20), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2018, 10, 15), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2018, 11, 5), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2018, 11, 12), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2018, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 1, 7), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2019, 3, 25), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2019, 4, 14), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 18), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2019, 4, 19), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2019, 6, 3), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2019, 6, 24), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2019, 7, 1), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2019, 7, 1), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2019, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2019, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2019, 8, 19), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2019, 10, 14), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2019, 11, 4), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2019, 11, 11), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2019, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 6), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2020, 3, 23), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2020, 4, 5), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 9), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2020, 4, 10), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2020, 5, 25), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2020, 6, 15), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2020, 6, 22), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2020, 6, 29), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2020, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2020, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2020, 8, 17), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2020, 10, 12), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2020, 11, 2), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2020, 11, 16), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2020, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 1, 11), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2021, 3, 22), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2021, 3, 28), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2021, 4, 1), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2021, 4, 2), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2021, 5, 17), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2021, 6, 7), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2021, 6, 14), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2021, 7, 5), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2021, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2021, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2021, 8, 16), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2021, 10, 18), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2021, 11, 1), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2021, 11, 15), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2021, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 10), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2022, 3, 21), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2022, 4, 10), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 14), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2022, 4, 15), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2022, 5, 30), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2022, 6, 20), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2022, 6, 27), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2022, 7, 4), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2022, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2022, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2022, 8, 15), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2022, 10, 17), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2022, 11, 7), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2022, 11, 14), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2022, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 9), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2023, 3, 20), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2023, 4, 2), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 6), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2023, 4, 7), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2023, 5, 22), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2023, 6, 12), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2023, 6, 19), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2023, 7, 3), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2023, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2023, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2023, 8, 21), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2023, 10, 16), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2023, 11, 6), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2023, 11, 13), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2023, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 1, 8), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2024, 3, 24), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2024, 3, 25), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2024, 3, 28), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2024, 3, 29), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2024, 5, 13), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2024, 6, 3), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2024, 6, 10), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2024, 7, 1), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2024, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2024, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2024, 8, 19), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2024, 10, 14), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2024, 11, 4), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2024, 11, 11), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2024, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 6), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2025, 3, 24), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2025, 4, 13), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 17), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2025, 6, 2), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2025, 6, 23), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2025, 6, 30), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2025, 6, 30), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2025, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2025, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2025, 8, 18), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2025, 10, 13), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2025, 11, 3), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2025, 11, 17), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2025, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 1, 12), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2026, 3, 23), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2026, 3, 29), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 2), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2026, 4, 3), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2026, 5, 18), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2026, 6, 8), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2026, 6, 15), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2026, 6, 29), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2026, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2026, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2026, 8, 17), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2026, 10, 12), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2026, 11, 2), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2026, 11, 16), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2026, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 1, 11), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2027, 3, 21), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2027, 3, 22), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2027, 3, 25), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2027, 3, 26), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2027, 5, 10), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2027, 5, 31), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2027, 6, 7), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2027, 7, 5), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2027, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2027, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2027, 8, 16), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2027, 10, 18), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2027, 11, 1), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2027, 11, 15), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2027, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 10), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2028, 3, 20), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2028, 4, 9), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 13), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2028, 5, 29), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2028, 6, 19), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2028, 6, 26), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2028, 7, 3), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2028, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2028, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2028, 8, 21), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2028, 10, 16), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2028, 11, 6), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2028, 11, 13), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2028, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 1, 8), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2029, 3, 19), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2029, 3, 25), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2029, 3, 29), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2029, 3, 30), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2029, 5, 14), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2029, 6, 4), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2029, 6, 11), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2029, 7, 2), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2029, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2029, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2029, 8, 20), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2029, 10, 15), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2029, 11, 5), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2029, 11, 12), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2029, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 1, 7), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2030, 3, 25), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2030, 4, 14), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 18), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2030, 4, 19), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2030, 6, 3), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2030, 6, 24), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2030, 7, 1), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2030, 7, 1), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2030, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2030, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2030, 8, 19), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2030, 10, 14), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2030, 11, 4), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2030, 11, 11), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2030, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 6), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2031, 3, 24), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2031, 4, 6), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 10), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2031, 5, 26), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2031, 6, 16), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2031, 6, 23), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2031, 6, 30), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2031, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2031, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2031, 8, 18), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2031, 10, 13), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2031, 11, 3), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2031, 11, 17), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2031, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 1, 12), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2032, 3, 21), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2032, 3, 22), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2032, 3, 25), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2032, 3, 26), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2032, 5, 10), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2032, 5, 31), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2032, 6, 7), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2032, 7, 5), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2032, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2032, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2032, 8, 16), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2032, 10, 18), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2032, 11, 1), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2032, 11, 15), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2032, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 10), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2033, 3, 21), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2033, 4, 10), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 14), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2033, 4, 15), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2033, 5, 30), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2033, 6, 20), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2033, 6, 27), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2033, 7, 4), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2033, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2033, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2033, 8, 15), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2033, 10, 17), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2033, 11, 7), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2033, 11, 14), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2033, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 9), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2034, 3, 20), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2034, 4, 2), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 6), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2034, 5, 22), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2034, 6, 12), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2034, 6, 19), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2034, 7, 3), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2034, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2034, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2034, 8, 21), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2034, 10, 16), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2034, 11, 6), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2034, 11, 13), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2034, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 1, 8), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2035, 3, 18), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2035, 3, 19), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2035, 3, 22), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2035, 3, 23), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2035, 5, 7), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2035, 5, 28), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2035, 6, 4), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2035, 7, 2), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2035, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2035, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2035, 8, 20), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2035, 10, 15), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2035, 11, 5), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2035, 11, 12), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2035, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 7), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2036, 3, 24), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2036, 4, 6), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 10), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2036, 4, 11), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2036, 5, 26), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2036, 6, 16), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2036, 6, 23), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2036, 6, 30), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2036, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2036, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2036, 8, 18), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2036, 10, 13), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2036, 11, 3), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2036, 11, 17), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2036, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 1, 12), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2037, 3, 23), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2037, 3, 29), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 2), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2037, 5, 18), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2037, 6, 8), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2037, 6, 15), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2037, 6, 29), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2037, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2037, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2037, 8, 17), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2037, 10, 12), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2037, 11, 2), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2037, 11, 16), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2037, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 1, 11), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2038, 3, 22), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2038, 4, 18), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 22), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2038, 6, 7), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2038, 6, 28), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2038, 7, 5), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2038, 7, 5), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2038, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2038, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2038, 8, 16), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2038, 10, 18), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2038, 11, 1), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2038, 11, 15), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2038, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 10), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2039, 3, 21), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2039, 4, 3), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 7), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2039, 4, 8), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2039, 5, 23), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2039, 6, 13), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2039, 6, 20), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2039, 7, 4), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2039, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2039, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2039, 8, 15), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2039, 10, 17), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2039, 11, 7), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2039, 11, 14), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2039, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 1, 9), "Día de los Reyes Magos", "Epiphany"),
          NationalHoliday.new(Date.new(2040, 3, 19), "Día de San José", "Saint Joseph's Day"),
          NationalHoliday.new(Date.new(2040, 3, 25), "Domingo de Ramos", "Palm Sunday"),
          NationalHoliday.new(Date.new(2040, 3, 29), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2040, 3, 30), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Domingo de Pascuas o Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2040, 5, 14), "Día de la Ascensión", "Ascension of Jesus"),
          NationalHoliday.new(Date.new(2040, 6, 4), "Corpus Christi", "Corpus Christi"),
          NationalHoliday.new(Date.new(2040, 6, 11), "Sagrado Corazón de Jesús", "The Sacred Heart of Jesus"),
          NationalHoliday.new(Date.new(2040, 7, 2), "San Pedro y San Pablo", "Saint Peter and Saint Paul"),
          NationalHoliday.new(Date.new(2040, 7, 20), "Declaracion de la Independencia de Colombia", "Independence Day"),
          NationalHoliday.new(Date.new(2040, 8, 7), "Batalla de Boyacá", "Battle of Boyacá"),
          NationalHoliday.new(Date.new(2040, 8, 20), "Asunción de la Virgen", "The Assumption of Mary"),
          NationalHoliday.new(Date.new(2040, 10, 15), "Día de la Raza", "Columbus Day"),
          NationalHoliday.new(Date.new(2040, 11, 5), "Día de todos los Santos", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2040, 11, 12), "Independencia de Cartagena", "Cartagena Independence Day"),
          NationalHoliday.new(Date.new(2040, 12, 8), "Día de la Inmaculada Concepción", "The Immaculate Conception"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Navidad", "Christmas Day")
        ]
      end
    end
  end
end
