module NationalHolidays
  module Countries
    class Croatia < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Croatia (all)', 'croatia01', self.zagreb) ]
      end

      def zagreb
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2011, 4, 24), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2011, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2011, 6, 23), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2011, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2011, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2011, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2011, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2011, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2011, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2012, 4, 8), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2012, 6, 7), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2012, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2012, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2012, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2012, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2012, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2012, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2013, 3, 31), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2013, 5, 30), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2013, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2013, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2013, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2013, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2013, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2013, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2014, 6, 19), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2014, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2014, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2014, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2014, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2014, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2014, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2015, 4, 5), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2015, 6, 4), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2015, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2015, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2015, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2015, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2015, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2015, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2016, 5, 26), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2016, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2016, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2016, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2016, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2016, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2016, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2017, 6, 15), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2017, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2017, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2017, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2017, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2017, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2017, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2018, 5, 31), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2018, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2018, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2018, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2018, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2018, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2018, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2019, 6, 20), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2019, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2019, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2019, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2019, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2019, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2019, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2020, 6, 11), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2020, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2020, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2020, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2020, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2020, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2020, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2021, 6, 3), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2021, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2021, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2021, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2021, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2021, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2021, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2022, 6, 16), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2022, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2022, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2022, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2022, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2022, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2022, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2023, 6, 8), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2023, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2023, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2023, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2023, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2023, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2023, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2024, 5, 30), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2024, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2024, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2024, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2024, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2024, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2024, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2025, 6, 19), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2025, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2025, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2025, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2025, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2025, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2025, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2026, 6, 4), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2026, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2026, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2026, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2026, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2026, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2026, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2027, 5, 27), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2027, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2027, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2027, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2027, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2027, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2027, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2028, 6, 15), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2028, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2028, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2028, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2028, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2028, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2028, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2029, 5, 31), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2029, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2029, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2029, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2029, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2029, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2029, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2030, 6, 20), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2030, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2030, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2030, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2030, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2030, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2030, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2031, 6, 12), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2031, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2031, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2031, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2031, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2031, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2031, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2032, 5, 27), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2032, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2032, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2032, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2032, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2032, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2032, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2033, 6, 16), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2033, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2033, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2033, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2033, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2033, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2033, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2034, 6, 8), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2034, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2034, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2034, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2034, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2034, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2034, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2035, 5, 24), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2035, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2035, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2035, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2035, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2035, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2035, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2036, 6, 12), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2036, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2036, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2036, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2036, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2036, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2036, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2037, 6, 4), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2037, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2037, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2037, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2037, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2037, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2037, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2038, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2038, 6, 24), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2038, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2038, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2038, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2038, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2038, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2039, 6, 9), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2039, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2039, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2039, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2039, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2039, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2039, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 1, 6), "Bogojavljanje ili Sveta tri kralja", "Epiphany"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Uskrs", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Uskrsni ponedjeljak", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Praznik rada", "Labour Day"),
          NationalHoliday.new(Date.new(2040, 5, 31), "Tijelovo", "Corpus Christi"),
          NationalHoliday.new(Date.new(2040, 6, 22), "Dan antifašističke borbe", "Anti-Fascist Struggle Day"),
          NationalHoliday.new(Date.new(2040, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2040, 8, 5), "Dan pobjede i domovinske zahvalnosti i Dan hrvatskih branitelja", "Victory and Homeland Thanksgiving Day and the Day of Croatian defenders"),
          NationalHoliday.new(Date.new(2040, 8, 15), "Velika Gospa", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2040, 10, 8), "Dan neovisnosti", "Independence Day"),
          NationalHoliday.new(Date.new(2040, 11, 1), "Svi sveti", "All Saints' Day"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Božić", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Prvi dan po Božiću, Sveti Stjepan", "St Stephen's Day")
        ]
      end
    end
  end
end
