module NationalHolidays
  module Countries
    class CzechRepublic < Country

      attr_reader :prague

      def default
        self.prague
      end

      def initialize
        @regions = [ 'Prague' ]

        @prague = [
          NationalHoliday.new(Date.new(2011, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2011, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2011, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2011, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2011, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2011, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2011, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2011, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2011, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2012, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2012, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2012, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2012, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2012, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2012, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2012, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2012, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2013, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2013, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2013, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2013, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2013, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2013, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2013, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2013, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2014, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2014, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2014, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2014, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2014, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2014, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2014, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2014, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2015, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2015, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2015, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2015, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2015, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2015, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2015, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2015, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2016, 3, 25), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2016, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2016, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2016, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2016, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2016, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2016, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2016, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2016, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2017, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2017, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2017, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2017, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2017, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2017, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2017, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2017, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2018, 3, 30), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2018, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2018, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2018, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2018, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2018, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2018, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2018, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2018, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2019, 4, 19), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2019, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2019, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2019, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2019, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2019, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2019, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2019, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2019, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2020, 4, 10), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2020, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2020, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2020, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2020, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2020, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2020, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2020, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2020, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2021, 4, 2), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2021, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2021, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2021, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2021, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2021, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2021, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2021, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2021, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2022, 4, 15), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2022, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2022, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2022, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2022, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2022, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2022, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2022, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2022, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2023, 4, 7), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2023, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2023, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2023, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2023, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2023, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2023, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2023, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2023, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2024, 3, 29), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2024, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2024, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2024, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2024, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2024, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2024, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2024, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2024, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2025, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2025, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2025, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2025, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2025, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2025, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2025, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2025, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2026, 4, 3), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2026, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2026, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2026, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2026, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2026, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2026, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2026, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2026, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2027, 3, 26), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2027, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2027, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2027, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2027, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2027, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2027, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2027, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2027, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2028, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2028, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2028, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2028, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2028, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2028, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2028, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2028, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2029, 3, 30), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2029, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2029, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2029, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2029, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2029, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2029, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2029, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2029, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2030, 4, 19), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2030, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2030, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2030, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2030, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2030, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2030, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2030, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2030, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2031, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2031, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2031, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2031, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2031, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2031, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2031, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2031, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2032, 3, 26), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2032, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2032, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2032, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2032, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2032, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2032, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2032, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2032, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2033, 4, 15), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2033, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2033, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2033, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2033, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2033, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2033, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2033, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2033, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2034, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2034, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2034, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2034, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2034, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2034, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2034, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2034, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2035, 3, 23), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2035, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2035, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2035, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2035, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2035, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2035, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2035, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2035, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2036, 4, 11), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2036, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2036, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2036, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2036, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2036, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2036, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2036, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2036, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2037, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2037, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2037, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2037, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2037, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2037, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2037, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2037, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2038, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2038, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2038, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2038, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2038, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2038, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2038, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2038, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2039, 4, 8), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2039, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2039, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2039, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2039, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2039, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2039, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2039, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2039, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "2. svátek vánoční", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Den obnovy samostatného českého státu", "Restoration Day of the Independent Czech State"),
          NationalHoliday.new(Date.new(2040, 3, 30), "Velký pátek", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Velikonoční pondělí", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Svátek práce", "Labour Day"),
          NationalHoliday.new(Date.new(2040, 5, 8), "Den vítězství", "Liberation Day"),
          NationalHoliday.new(Date.new(2040, 7, 5), "Den slovanských věrozvěstů Cyrila a Metoděje", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2040, 7, 6), "Den upálení mistra Jana Husa", "Jan Hus Day"),
          NationalHoliday.new(Date.new(2040, 9, 28), "Den české státnosti", "St. Wenceslas Day (Czech Statehood Day)"),
          NationalHoliday.new(Date.new(2040, 10, 28), "Den vzniku samostatného československého státu", "Independent Czechoslovak State Day"),
          NationalHoliday.new(Date.new(2040, 11, 17), "Den boje za svobodu a demokracii", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2040, 12, 24), "Štědrý den", "Christmas Eve"),
          NationalHoliday.new(Date.new(2040, 12, 25), "1. svátek vánoční", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "2. svátek vánoční", "St. Stephen's Day")
        ]
      end
    end
  end
end
