module NationalHolidays
  module Countries
    class Estonia < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Estonia (all)', 'estonia01', self.harju_maakond) ]
      end

      def harju_maakond
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2011, 4, 22), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2011, 4, 24), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2011, 6, 12), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2011, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2011, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2011, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2011, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2011, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2012, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2012, 4, 6), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2012, 4, 8), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2012, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2012, 5, 27), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2012, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2012, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2012, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2012, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2012, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2013, 3, 29), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2013, 3, 31), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2013, 5, 19), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2013, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2013, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2013, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2013, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2013, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2014, 4, 18), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2014, 4, 20), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2014, 6, 8), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2014, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2014, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2014, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2014, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2014, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2015, 4, 3), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2015, 4, 5), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2015, 5, 24), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2015, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2015, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2015, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2015, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2015, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2016, 3, 25), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 27), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2016, 5, 15), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2016, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2016, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2016, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2016, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2016, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2017, 4, 14), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 16), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2017, 6, 4), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2017, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2017, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2017, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2017, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2017, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2018, 3, 30), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 1), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2018, 5, 20), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2018, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2018, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2018, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2018, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2018, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2019, 4, 19), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 21), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2019, 6, 9), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2019, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2019, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2019, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2019, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2019, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2020, 4, 10), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 12), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2020, 5, 31), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2020, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2020, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2020, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2020, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2020, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2021, 4, 2), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 4), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2021, 5, 23), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2021, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2021, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2021, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2021, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2021, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2022, 4, 15), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 17), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2022, 6, 5), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2022, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2022, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2022, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2022, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2022, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2023, 4, 7), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 9), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2023, 5, 28), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2023, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2023, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2023, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2023, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2023, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2024, 3, 29), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 3, 31), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2024, 5, 19), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2024, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2024, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2024, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2024, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2024, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2025, 4, 18), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 20), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2025, 6, 8), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2025, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2025, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2025, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2025, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2025, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2026, 4, 3), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 5), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2026, 5, 24), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2026, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2026, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2026, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2026, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2026, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2027, 3, 26), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 28), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2027, 5, 16), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2027, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2027, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2027, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2027, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2027, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2028, 4, 14), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 16), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2028, 6, 4), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2028, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2028, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2028, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2028, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2028, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2029, 3, 30), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 1), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2029, 5, 20), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2029, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2029, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2029, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2029, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2029, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2030, 4, 19), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 21), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2030, 6, 9), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2030, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2030, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2030, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2030, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2030, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2031, 4, 11), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 13), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2031, 6, 1), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2031, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2031, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2031, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2031, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2031, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2032, 3, 26), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 28), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2032, 5, 16), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2032, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2032, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2032, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2032, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2032, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2033, 4, 15), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 17), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2033, 6, 5), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2033, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2033, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2033, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2033, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2033, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2034, 4, 7), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 9), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2034, 5, 28), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2034, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2034, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2034, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2034, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2034, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2035, 3, 23), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 25), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2035, 5, 13), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2035, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2035, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2035, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2035, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2035, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2036, 4, 11), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 13), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2036, 6, 1), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2036, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2036, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2036, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2036, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2036, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2037, 4, 3), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 5), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2037, 5, 24), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2037, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2037, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2037, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2037, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2037, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2038, 4, 23), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 25), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2038, 6, 13), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2038, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2038, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2038, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2038, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2038, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2039, 4, 8), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 10), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2039, 5, 29), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2039, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2039, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2039, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2039, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2039, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "teine jõulupüha", "Boxing Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "uusaasta", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 2, 24), "iseseisvuspäev", "Independence Day"),
          NationalHoliday.new(Date.new(2040, 3, 30), "suur reede", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 1), "ülestõusmispühade 1. püha", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "kevadpüha", "Spring Day (May Day)"),
          NationalHoliday.new(Date.new(2040, 5, 20), "nelipühade 1. püha", "Whit Sunday"),
          NationalHoliday.new(Date.new(2040, 6, 23), "võidupüha", "Victory Day"),
          NationalHoliday.new(Date.new(2040, 6, 24), "jaanipäev", "St. John's Day (Midsummer Day)"),
          NationalHoliday.new(Date.new(2040, 8, 20), "taasiseseisvumispäev", "Day of Restoration of Independence"),
          NationalHoliday.new(Date.new(2040, 12, 24), "jõululaupäev", "Christmas Eve"),
          NationalHoliday.new(Date.new(2040, 12, 25), "esimene jõulupüha", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "teine jõulupüha", "Boxing Day")
        ]
      end

    end
  end
end
