module NationalHolidays
  module Countries
    class HongKong < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Hong Kong (all)', 'hong_kong01', self.hong_kong) ]
      end

      def hong_kong
        [
          NationalHoliday.new(Date.new(2013, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 2, 11), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2013, 2, 12), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2013, 2, 13), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2013, 3, 29), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2013, 3, 30), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 4, 4), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2013, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2013, 5, 17), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2013, 6, 12), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2013, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2013, 9, 20), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2013, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2013, 10, 14), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2013, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 1, 31), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2014, 2, 1), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2014, 2, 3), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2014, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2014, 4, 18), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2014, 4, 19), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2014, 5, 6), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2014, 6, 2), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2014, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2014, 9, 9), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2014, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2014, 10, 2), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2014, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 2, 19), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2015, 2, 20), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2015, 2, 21), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2015, 4, 3), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2015, 4, 4), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 4, 7), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2015, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2015, 5, 25), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2015, 6, 20), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2015, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2015, 9, 28), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2015, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2015, 10, 21), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2015, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 2, 8), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2016, 2, 9), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2016, 2, 10), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2016, 3, 25), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 26), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 4, 4), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2016, 5, 2), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2016, 5, 14), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2016, 6, 9), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2016, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2016, 9, 16), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2016, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2016, 10, 10), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2016, 12, 26), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 27), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2017, 1, 2), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 28), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2017, 1, 30), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2017, 1, 31), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2017, 4, 4), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2017, 4, 14), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 15), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2017, 5, 3), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2017, 5, 30), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2017, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2017, 10, 2), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2017, 10, 5), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2017, 10, 28), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2017, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 2, 16), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2018, 2, 17), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2018, 2, 19), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2018, 3, 30), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 3, 31), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2018, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2018, 5, 22), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2018, 6, 18), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2018, 7, 2), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2018, 9, 25), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2018, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2018, 10, 17), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2018, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 2, 5), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2019, 2, 6), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2019, 2, 7), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2019, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2019, 4, 19), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 20), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2019, 5, 13), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2019, 6, 7), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2019, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2019, 9, 14), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2019, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2019, 10, 7), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2019, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 25), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2020, 1, 27), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2020, 1, 28), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2020, 4, 4), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2020, 4, 10), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 11), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 4, 30), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2020, 6, 25), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2020, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2020, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2020, 10, 2), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2020, 10, 26), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2020, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 2, 12), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2021, 2, 13), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2021, 2, 15), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2021, 4, 2), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 3), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 4, 6), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2021, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2021, 5, 19), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2021, 6, 14), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2021, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2021, 9, 22), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2021, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2021, 10, 14), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2021, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 27), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 2, 1), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2022, 2, 2), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2022, 2, 3), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2022, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2022, 4, 15), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 16), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 2), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2022, 5, 9), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2022, 6, 3), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2022, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2022, 9, 12), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2022, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2022, 10, 4), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2022, 12, 26), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 27), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2023, 1, 2), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 23), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2023, 1, 24), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2023, 1, 25), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2023, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2023, 4, 7), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 8), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2023, 5, 26), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2023, 6, 22), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2023, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2023, 9, 30), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2023, 10, 2), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2023, 10, 23), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2023, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 2, 10), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2024, 2, 12), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2024, 2, 13), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2024, 3, 29), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 3, 30), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 4, 4), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2024, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2024, 5, 15), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2024, 6, 10), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2024, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2024, 9, 18), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2024, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2024, 10, 11), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2024, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 29), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2025, 1, 30), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2025, 1, 31), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2025, 4, 4), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2025, 4, 18), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 19), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2025, 5, 5), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2025, 5, 31), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2025, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2025, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2025, 10, 7), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2025, 10, 29), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2025, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 2, 17), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2026, 2, 18), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2026, 2, 19), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2026, 4, 3), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 4), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 4, 7), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2026, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2026, 5, 25), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2026, 6, 19), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2026, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2026, 9, 26), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2026, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2026, 10, 19), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2026, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 2, 6), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2027, 2, 8), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2027, 2, 9), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2027, 3, 26), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 27), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2027, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2027, 5, 13), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2027, 6, 9), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2027, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2027, 9, 16), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2027, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2027, 10, 8), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2027, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 27), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 26), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2028, 1, 27), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2028, 1, 28), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2028, 4, 4), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2028, 4, 14), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 15), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2028, 5, 2), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2028, 5, 29), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2028, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2028, 10, 2), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2028, 10, 4), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2028, 10, 26), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2028, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 2, 13), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2029, 2, 14), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2029, 2, 15), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2029, 3, 30), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 3, 31), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 4, 4), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2029, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2029, 5, 21), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2029, 6, 16), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2029, 7, 2), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2029, 9, 24), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2029, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2029, 10, 16), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2029, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 2, 4), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2030, 2, 5), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2030, 2, 6), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2030, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2030, 4, 19), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 20), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2030, 5, 9), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2030, 6, 5), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2030, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2030, 9, 13), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2030, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2030, 10, 5), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2030, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 23), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2031, 1, 24), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2031, 1, 25), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2031, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2031, 4, 11), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 12), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2031, 5, 28), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2031, 6, 24), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2031, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2031, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2031, 10, 2), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2031, 10, 24), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2031, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 2, 11), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2032, 2, 12), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2032, 2, 13), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2032, 3, 26), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 27), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2032, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2032, 5, 17), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2032, 6, 12), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2032, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2032, 9, 20), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2032, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2032, 10, 12), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2032, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 27), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 31), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2033, 2, 1), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2033, 2, 2), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2033, 4, 4), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2033, 4, 15), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 16), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 2), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2033, 5, 6), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2033, 6, 1), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2033, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2033, 9, 9), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2033, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2033, 10, 2), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2033, 12, 26), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 27), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2034, 1, 2), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 2, 20), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2034, 2, 21), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2034, 2, 22), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2034, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2034, 4, 7), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 8), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2034, 5, 25), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2034, 6, 20), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2034, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2034, 9, 28), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2034, 10, 2), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2034, 10, 20), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2034, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 2, 8), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2035, 2, 9), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2035, 2, 10), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2035, 3, 23), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 24), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2035, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2035, 5, 15), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2035, 6, 11), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2035, 7, 2), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2035, 9, 17), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2035, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2035, 10, 9), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2035, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 28), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2036, 1, 29), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2036, 1, 30), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2036, 4, 4), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2036, 4, 11), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 12), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2036, 5, 3), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2036, 5, 30), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2036, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2036, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2036, 10, 6), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2036, 10, 27), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2036, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 2, 16), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2037, 2, 17), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2037, 2, 18), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2037, 4, 3), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 4), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2037, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2037, 4, 6), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2037, 5, 22), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2037, 6, 18), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2037, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2037, 9, 25), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2037, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2037, 10, 17), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2037, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 2, 4), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2038, 2, 5), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2038, 2, 6), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2038, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2038, 4, 23), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 24), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2038, 5, 11), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2038, 6, 7), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2038, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2038, 9, 14), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2038, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2038, 10, 7), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2038, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 27), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 24), "農曆年初一 / Chinese New Year", "Chinese New Year"),
          NationalHoliday.new(Date.new(2039, 1, 25), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2039, 1, 26), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2039, 4, 5), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2039, 4, 8), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 9), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 4, 30), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2039, 5, 2), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2039, 5, 27), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2039, 7, 1), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2039, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2039, 10, 3), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2039, 10, 26), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2039, 12, 26), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 27), "聖誕節翌日 / Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2040, 1, 2), "元旦新年 / New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 2, 13), "農曆年初二 / The second day of Chinese New Year", "The second day of Chinese New Year"),
          NationalHoliday.new(Date.new(2040, 2, 14), "農曆年初三 / The third day of Chinese New Year", "The third day of Chinese New Year"),
          NationalHoliday.new(Date.new(2040, 2, 15), "農曆年初四 / The fourth day of Chinese New Year", "The fourth day of Chinese New Year"),
          NationalHoliday.new(Date.new(2040, 3, 30), "耶穌受難節 / Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 3, 31), "耶穌受難節翌日 / Easter Saturday", "Easter Saturday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "復活節星期一 / Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 4, 4), "清明節 / Ching Ming Festival", "Ching Ming Festival"),
          NationalHoliday.new(Date.new(2040, 5, 1), "勞動節 / Labour Day", "Labour Day"),
          NationalHoliday.new(Date.new(2040, 5, 18), "佛誕 / Buddha's Birthday", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2040, 6, 14), "端午節 / Dragon Boat Festival (Tuen Ng Festival)", "Dragon Boat Festival (Tuen Ng Festival)"),
          NationalHoliday.new(Date.new(2040, 7, 2), "香港特別行政區成立紀念日 / Hong Kong Special Administrative Region Establishment Day", "Hong Kong Special Administrative Region Establishment Day"),
          NationalHoliday.new(Date.new(2040, 9, 21), "中秋節翌日 / Day following the Mid-Autumn Festival", "Day following the Mid-Autumn Festival"),
          NationalHoliday.new(Date.new(2040, 10, 1), "中華人民共和國國慶日 / National Day", "National Day"),
          NationalHoliday.new(Date.new(2040, 10, 15), "重陽節 / Chung Yeung Festival", "Chung Yeung Festival"),
          NationalHoliday.new(Date.new(2040, 12, 25), "聖誕節 / Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "聖誕節翌日 / Boxing Day", "Boxing Day")
        ]
      end

    end
  end
end
