module NationalHolidays
  module Countries
    class Hungary < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Hungary (all)', 'hungary01', self.budapest) ]
      end

      def budapest
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 3, 14), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2011, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2011, 4, 24), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2011, 6, 12), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2011, 6, 13), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2011, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2011, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2011, 10, 31), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2011, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2011, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2012, 3, 16), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2012, 4, 8), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 4, 30), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2012, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2012, 5, 27), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2012, 5, 28), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2012, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2012, 10, 22), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2012, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2012, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2012, 11, 2), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2012, 12, 24), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2012, 12, 31), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2013, 3, 31), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2013, 5, 19), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2013, 5, 20), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2013, 8, 19), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2013, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2013, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2013, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2013, 12, 24), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2013, 12, 27), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2014, 5, 2), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2014, 6, 8), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2014, 6, 9), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2014, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2014, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2014, 10, 24), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2014, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2014, 12, 24), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 2), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2015, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2015, 4, 5), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2015, 5, 24), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2015, 5, 25), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2015, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2015, 8, 21), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2015, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2015, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2015, 12, 24), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 3, 14), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2016, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2016, 5, 15), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2016, 5, 16), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2016, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2016, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2016, 10, 31), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2016, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2016, 12, 24), "Pihenőnap", "Rest Day"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2017, 6, 4), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2017, 6, 5), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2017, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2017, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2017, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2018, 5, 20), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2018, 5, 21), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2018, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2018, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2018, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2019, 6, 9), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2019, 6, 10), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2019, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2019, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2019, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2020, 5, 31), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2020, 6, 1), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2020, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2020, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2020, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2021, 5, 23), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2021, 5, 24), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2021, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2021, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2021, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2022, 6, 5), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2022, 6, 6), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2022, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2022, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2022, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2023, 5, 28), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2023, 5, 29), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2023, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2023, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2023, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2024, 5, 19), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2024, 5, 20), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2024, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2024, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2024, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2025, 6, 8), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2025, 6, 9), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2025, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2025, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2025, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2026, 5, 24), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2026, 5, 25), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2026, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2026, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2026, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2027, 5, 16), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2027, 5, 17), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2027, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2027, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2027, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2028, 6, 4), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2028, 6, 5), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2028, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2028, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2028, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2029, 5, 20), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2029, 5, 21), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2029, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2029, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2029, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2030, 6, 9), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2030, 6, 10), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2030, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2030, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2030, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2031, 6, 1), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2031, 6, 2), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2031, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2031, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2031, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2032, 5, 16), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2032, 5, 17), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2032, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2032, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2032, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2033, 6, 5), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2033, 6, 6), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2033, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2033, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2033, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2034, 5, 28), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2034, 5, 29), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2034, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2034, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2034, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2035, 5, 13), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2035, 5, 14), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2035, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2035, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2035, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2036, 6, 1), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2036, 6, 2), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2036, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2036, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2036, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2037, 5, 24), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2037, 5, 25), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2037, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2037, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2037, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2038, 6, 13), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2038, 6, 14), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2038, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2038, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2038, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2039, 5, 29), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2039, 5, 30), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2039, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2039, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2039, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Karácsony másnapja", "Second Day of Christmas"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Újév", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 3, 15), "Nemzeti ünnep", "National Day (Anniversary of the Revolution 1848-49)"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Húsvétvasárnap", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Húsvéthétfő", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "A munka ünnepe", "Labour Day"),
          NationalHoliday.new(Date.new(2040, 5, 20), "Pünkösdvasárnap", "Whit Sunday"),
          NationalHoliday.new(Date.new(2040, 5, 21), "Pünkösdhétfő", "Whit Monday"),
          NationalHoliday.new(Date.new(2040, 8, 20), "Szent István ünnepe", "Saint Stephen's Day"),
          NationalHoliday.new(Date.new(2040, 10, 23), "Nemzeti ünnep", "National Day (Proclamation of the Republic / Anniversary of the Revolution 1956)"),
          NationalHoliday.new(Date.new(2040, 11, 1), "Mindenszentek", "All Saints' Day"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Karácsony", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Karácsony másnapja", "Second Day of Christmas")
        ]
      end

    end
  end
end
