module NationalHolidays
  module Countries
    class Iceland < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Iceland (all)', 'iceland01', self.reykjavik) ]
      end

      def reykjavik
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 4, 21), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2011, 4, 21), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2011, 4, 22), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2011, 4, 24), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2011, 6, 2), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2011, 6, 12), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2011, 6, 13), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2011, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2011, 8, 1), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2011, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2011, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2011, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 4, 5), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2012, 4, 6), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2012, 4, 8), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 4, 19), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2012, 5, 17), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2012, 5, 27), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2012, 5, 28), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2012, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2012, 8, 6), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2012, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2012, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 3, 28), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2013, 3, 29), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2013, 3, 31), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 4, 25), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2013, 5, 9), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2013, 5, 19), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2013, 5, 20), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2013, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2013, 8, 5), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2013, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2013, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 4, 17), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2014, 4, 18), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 4, 24), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2014, 5, 29), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2014, 6, 8), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2014, 6, 9), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2014, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2014, 8, 4), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2014, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2014, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 4, 2), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2015, 4, 3), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2015, 4, 5), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 4, 23), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2015, 5, 14), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2015, 5, 24), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2015, 5, 25), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2015, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2015, 8, 3), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2015, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2015, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 3, 24), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2016, 3, 25), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 4, 21), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2016, 5, 5), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2016, 5, 15), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2016, 5, 16), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2016, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2016, 8, 1), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2016, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2016, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 4, 13), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 4, 20), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2017, 5, 25), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2017, 6, 4), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2017, 6, 5), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2017, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2017, 8, 7), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2017, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2017, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 3, 29), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2018, 3, 30), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 4, 19), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2018, 5, 10), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2018, 5, 20), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2018, 5, 21), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2018, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2018, 8, 6), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2018, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2018, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 4, 18), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2019, 4, 19), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 4, 25), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2019, 5, 30), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2019, 6, 9), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2019, 6, 10), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2019, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2019, 8, 5), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2019, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2019, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 4, 9), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2020, 4, 10), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 4, 23), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2020, 5, 21), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2020, 5, 31), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2020, 6, 1), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2020, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2020, 8, 3), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2020, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2020, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 4, 1), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2021, 4, 2), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 4, 22), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2021, 5, 13), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2021, 5, 23), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2021, 5, 24), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2021, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2021, 8, 2), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2021, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2021, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 4, 14), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2022, 4, 15), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 4, 21), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2022, 5, 26), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2022, 6, 5), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2022, 6, 6), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2022, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2022, 8, 1), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2022, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2022, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 4, 6), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2023, 4, 7), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 4, 20), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2023, 5, 18), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2023, 5, 28), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2023, 5, 29), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2023, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2023, 8, 7), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2023, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2023, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 3, 28), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2024, 3, 29), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 4, 25), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2024, 5, 9), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2024, 5, 19), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2024, 5, 20), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2024, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2024, 8, 5), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2024, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2024, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 4, 17), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 4, 24), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2025, 5, 29), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2025, 6, 8), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2025, 6, 9), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2025, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2025, 8, 4), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2025, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2025, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 4, 2), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2026, 4, 3), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 4, 23), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2026, 5, 14), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2026, 5, 24), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2026, 5, 25), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2026, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2026, 8, 3), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2026, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2026, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 3, 25), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2027, 3, 26), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 4, 22), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2027, 5, 6), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2027, 5, 16), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2027, 5, 17), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2027, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2027, 8, 2), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2027, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2027, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 4, 13), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 4, 20), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2028, 5, 25), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2028, 6, 4), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2028, 6, 5), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2028, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2028, 8, 7), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2028, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2028, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 3, 29), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2029, 3, 30), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 4, 19), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2029, 5, 10), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2029, 5, 20), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2029, 5, 21), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2029, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2029, 8, 6), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2029, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2029, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 4, 18), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2030, 4, 19), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 4, 25), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2030, 5, 30), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2030, 6, 9), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2030, 6, 10), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2030, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2030, 8, 5), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2030, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2030, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 4, 10), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 4, 24), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2031, 5, 22), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2031, 6, 1), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2031, 6, 2), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2031, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2031, 8, 4), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2031, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2031, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 3, 25), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2032, 3, 26), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 4, 22), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2032, 5, 6), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2032, 5, 16), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2032, 5, 17), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2032, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2032, 8, 2), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2032, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2032, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 4, 14), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2033, 4, 15), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 4, 21), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2033, 5, 26), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2033, 6, 5), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2033, 6, 6), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2033, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2033, 8, 1), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2033, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2033, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 4, 6), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 4, 20), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2034, 5, 18), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2034, 5, 28), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2034, 5, 29), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2034, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2034, 8, 7), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2034, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2034, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 3, 22), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2035, 3, 23), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 4, 19), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2035, 5, 3), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2035, 5, 13), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2035, 5, 14), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2035, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2035, 8, 6), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2035, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2035, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 4, 10), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2036, 4, 11), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 4, 24), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2036, 5, 22), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2036, 6, 1), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2036, 6, 2), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2036, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2036, 8, 4), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2036, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2036, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 4, 2), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 4, 23), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2037, 5, 14), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2037, 5, 24), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2037, 5, 25), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2037, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2037, 8, 3), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2037, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2037, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 4, 22), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2038, 4, 22), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2038, 6, 3), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2038, 6, 13), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2038, 6, 14), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2038, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2038, 8, 2), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2038, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2038, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 4, 7), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2039, 4, 8), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 4, 21), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2039, 5, 19), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2039, 5, 29), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2039, 5, 30), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2039, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2039, 8, 1), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2039, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2039, 12, 31), "Gamlárskvöld", "New Year's Eve"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Nýársdagur", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 3, 29), "Skírdagur", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2040, 3, 30), "Föstudaginn langi", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Páskadagur", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Annar í páskum", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 4, 19), "Sumardagurinn fyrsti", "First Day of Summer"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Verkalýðsdagurinn", "Labour Day"),
          NationalHoliday.new(Date.new(2040, 5, 10), "Uppstigningardagur", "Ascension Day"),
          NationalHoliday.new(Date.new(2040, 5, 20), "Hvítasunnudagur", "Whit Sunday"),
          NationalHoliday.new(Date.new(2040, 5, 21), "Annar í hvítasunnu", "Whit Monday"),
          NationalHoliday.new(Date.new(2040, 6, 17), "Lýðveldisdagurinn", "National Day"),
          NationalHoliday.new(Date.new(2040, 8, 6), "Frídagur verslunarmanna", "Bank Holiday Monday"),
          NationalHoliday.new(Date.new(2040, 12, 24), "Jól", "Christmas Eve"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Jól", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Jól", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2040, 12, 31), "Gamlárskvöld", "New Year's Eve")
        ]
      end

    end
  end
end
