module NationalHolidays
  module Countries
    class Israel < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Israel (all)', 'israel01', self.jerusalem) ]
      end

      def jerusalem
        [
          NationalHoliday.new(Date.new(2014, 3, 16), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2014, 3, 17), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2014, 4, 15), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2014, 4, 21), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2014, 5, 6), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2014, 6, 4), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2014, 8, 5), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2014, 9, 25), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2014, 9, 26), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2014, 10, 4), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2014, 10, 9), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2014, 10, 16), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2015, 3, 5), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2015, 3, 6), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2015, 4, 4), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2015, 4, 10), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2015, 4, 23), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2015, 5, 24), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2015, 7, 26), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2015, 9, 14), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2015, 9, 15), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2015, 9, 23), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2015, 9, 28), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2015, 10, 5), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2016, 3, 24), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2016, 3, 25), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2016, 4, 23), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2016, 4, 29), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2016, 5, 12), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2016, 6, 12), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2016, 8, 14), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2016, 10, 3), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2016, 10, 4), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2016, 10, 12), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2016, 10, 17), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2016, 10, 24), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2017, 3, 12), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2017, 3, 13), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2017, 4, 11), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2017, 4, 17), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2017, 5, 2), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2017, 5, 31), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2017, 8, 1), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2017, 9, 21), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2017, 9, 22), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2017, 9, 30), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2017, 10, 5), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2017, 10, 12), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2018, 3, 1), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2018, 3, 2), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2018, 3, 31), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2018, 4, 6), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2018, 4, 19), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2018, 5, 20), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2018, 7, 22), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2018, 9, 10), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2018, 9, 11), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2018, 9, 19), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2018, 9, 24), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2018, 10, 1), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2019, 3, 21), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2019, 3, 22), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2019, 4, 20), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2019, 4, 26), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2019, 5, 9), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2019, 6, 9), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2019, 8, 11), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2019, 9, 30), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2019, 10, 1), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2019, 10, 9), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2019, 10, 14), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2019, 10, 21), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2020, 3, 10), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2020, 3, 11), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2020, 4, 9), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2020, 4, 15), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2020, 4, 29), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2020, 5, 29), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2020, 7, 30), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2020, 9, 19), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2020, 9, 20), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2020, 9, 28), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2020, 10, 3), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2020, 10, 10), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2021, 2, 26), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2021, 2, 27), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2021, 3, 28), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2021, 4, 3), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2021, 4, 15), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2021, 5, 17), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2021, 7, 18), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2021, 9, 7), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2021, 9, 8), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2021, 9, 16), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2021, 9, 21), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2021, 9, 28), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2022, 3, 17), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2022, 3, 18), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2022, 4, 16), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2022, 4, 22), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2022, 5, 5), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2022, 6, 5), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2022, 8, 7), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2022, 9, 26), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2022, 9, 27), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2022, 10, 5), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2022, 10, 10), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2022, 10, 17), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2023, 3, 7), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2023, 3, 8), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2023, 4, 6), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2023, 4, 12), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2023, 4, 26), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2023, 5, 26), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2023, 7, 27), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2023, 9, 16), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2023, 9, 17), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2023, 9, 25), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2023, 9, 30), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2023, 10, 7), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2024, 3, 24), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2024, 3, 25), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2024, 4, 23), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2024, 4, 29), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2024, 5, 14), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2024, 6, 12), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2024, 8, 13), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2024, 10, 3), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2024, 10, 4), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2024, 10, 12), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2024, 10, 17), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2024, 10, 24), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2025, 3, 14), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2025, 3, 15), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2025, 4, 13), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2025, 4, 19), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2025, 5, 1), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2025, 6, 2), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2025, 8, 3), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2025, 9, 23), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2025, 9, 24), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2025, 10, 2), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2025, 10, 7), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2025, 10, 14), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2026, 3, 3), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2026, 3, 4), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2026, 4, 2), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2026, 4, 8), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2026, 4, 22), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2026, 5, 22), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2026, 7, 23), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2026, 9, 12), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2026, 9, 13), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2026, 9, 21), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2026, 9, 26), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2026, 10, 3), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2027, 3, 23), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2027, 3, 24), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2027, 4, 22), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2027, 4, 28), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2027, 5, 12), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2027, 6, 11), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2027, 8, 12), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2027, 10, 2), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2027, 10, 3), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2027, 10, 11), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2027, 10, 16), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2027, 10, 23), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2028, 3, 12), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2028, 3, 13), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2028, 4, 11), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2028, 4, 17), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2028, 5, 2), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2028, 5, 31), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2028, 8, 1), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2028, 9, 21), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2028, 9, 22), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2028, 9, 30), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2028, 10, 5), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2028, 10, 12), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2029, 3, 1), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2029, 3, 2), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2029, 3, 31), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2029, 4, 6), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2029, 4, 19), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2029, 5, 20), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2029, 7, 22), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2029, 9, 10), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2029, 9, 11), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2029, 9, 19), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2029, 9, 24), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2029, 10, 1), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2030, 3, 19), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2030, 3, 20), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2030, 4, 18), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2030, 4, 24), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2030, 5, 8), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2030, 6, 7), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2030, 8, 8), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2030, 9, 28), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2030, 9, 29), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2030, 10, 7), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2030, 10, 12), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2030, 10, 19), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2031, 3, 9), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2031, 3, 10), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2031, 4, 8), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2031, 4, 14), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2031, 4, 29), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2031, 5, 28), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2031, 7, 29), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2031, 9, 18), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2031, 9, 19), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2031, 9, 27), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2031, 10, 2), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2031, 10, 9), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2032, 2, 26), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2032, 2, 27), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2032, 3, 27), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2032, 4, 2), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2032, 4, 15), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2032, 5, 16), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2032, 7, 18), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2032, 9, 6), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2032, 9, 7), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2032, 9, 15), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2032, 9, 20), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2032, 9, 27), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2033, 3, 15), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2033, 3, 16), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2033, 4, 14), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2033, 4, 20), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2033, 5, 4), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2033, 6, 3), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2033, 8, 4), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2033, 9, 24), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2033, 9, 25), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2033, 10, 3), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2033, 10, 8), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2033, 10, 15), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2034, 3, 5), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2034, 3, 6), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2034, 4, 4), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2034, 4, 10), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2034, 4, 25), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2034, 5, 24), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2034, 7, 25), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2034, 9, 14), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2034, 9, 15), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2034, 9, 23), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2034, 9, 28), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2034, 10, 5), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2035, 3, 25), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2035, 3, 26), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2035, 4, 24), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2035, 4, 30), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2035, 5, 15), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2035, 6, 13), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2035, 8, 14), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2035, 10, 4), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2035, 10, 5), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2035, 10, 13), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2035, 10, 18), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2035, 10, 25), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2036, 3, 13), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2036, 3, 14), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2036, 4, 12), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2036, 4, 18), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2036, 5, 1), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2036, 6, 1), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2036, 8, 3), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2036, 9, 22), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2036, 9, 23), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2036, 10, 1), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2036, 10, 6), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2036, 10, 13), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2037, 3, 1), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2037, 3, 2), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2037, 3, 31), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2037, 4, 6), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2037, 4, 21), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2037, 5, 20), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2037, 7, 21), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2037, 9, 10), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2037, 9, 11), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2037, 9, 19), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2037, 9, 24), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2037, 10, 1), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2038, 3, 21), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2038, 3, 22), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2038, 4, 20), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2038, 4, 26), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2038, 5, 11), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2038, 6, 9), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2038, 8, 10), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2038, 9, 30), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2038, 10, 1), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2038, 10, 9), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2038, 10, 14), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2038, 10, 21), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2039, 3, 10), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2039, 3, 11), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2039, 4, 9), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2039, 4, 15), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2039, 4, 28), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2039, 5, 29), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2039, 7, 31), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2039, 9, 19), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2039, 9, 20), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2039, 9, 28), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2039, 10, 3), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2039, 10, 10), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2040, 2, 28), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2040, 2, 29), "פורים (Purim)", "Feast of Purim"),
          NationalHoliday.new(Date.new(2040, 3, 29), "פסח (Pesach)", "Passover"),
          NationalHoliday.new(Date.new(2040, 4, 4), "שביעי של פסח (Shvi'i shel Pesach)", "Seventh day of Passover"),
          NationalHoliday.new(Date.new(2040, 4, 18), "יום העצמאות (Yom Ha-Atzmaut)", "Independence Day"),
          NationalHoliday.new(Date.new(2040, 5, 18), "שבועות (Shavuot)", "Feast of Shavuot (Pentecost)"),
          NationalHoliday.new(Date.new(2040, 7, 19), "תשעה באב (Tisha B'Av)", "Fast of Ninth of Av"),
          NationalHoliday.new(Date.new(2040, 9, 8), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2040, 9, 9), "ראש השנה (Rosh Hashanah)", "Rosh Hashanah (New Year)"),
          NationalHoliday.new(Date.new(2040, 9, 17), "יום כיפור (Yom Kippur)", "Day of Atonement (Yom Kippur)"),
          NationalHoliday.new(Date.new(2040, 9, 22), "סוכות (Sukkot)", "First Day of Sucot (Tabernacles)"),
          NationalHoliday.new(Date.new(2040, 9, 29), "שמחת תורה/שמיני עצרת (Simchat Torah/Shemini Atzeret)", "Last Day of Sucot (Tabernacles)")
        ]
      end

    end
  end
end
