module NationalHolidays
  module Countries
    class Japan < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Japan (all)', 'japan01', self.kanto) ]
      end

      def kanto
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 1, 10), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2011, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2011, 3, 21), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2011, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2011, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2011, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2011, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2011, 7, 18), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2011, 9, 19), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2011, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2011, 10, 10), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2011, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2011, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2011, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2012, 1, 2), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 1, 9), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2012, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2012, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2012, 4, 30), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2012, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2012, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2012, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2012, 7, 16), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2012, 9, 17), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2012, 9, 22), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2012, 10, 8), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2012, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2012, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2012, 12, 24), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2013, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 1, 14), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2013, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2013, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2013, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2013, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2013, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2013, 5, 6), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2013, 7, 15), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2013, 9, 16), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2013, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2013, 10, 14), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2013, 11, 4), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2013, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2013, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2014, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 1, 13), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2014, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2014, 3, 21), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2014, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2014, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2014, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2014, 5, 6), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2014, 7, 21), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2014, 9, 15), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2014, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2014, 10, 13), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2014, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2014, 11, 24), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2014, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2015, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 12), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2015, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2015, 3, 21), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2015, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2015, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2015, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2015, 5, 6), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2015, 7, 20), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2015, 9, 21), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2015, 9, 22), "国民の休日 Kyujitsu", "Holiday by Law"),
          NationalHoliday.new(Date.new(2015, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2015, 10, 12), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2015, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2015, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2015, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2016, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 1, 11), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2016, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2016, 3, 21), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2016, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2016, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2016, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2016, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2016, 7, 18), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2016, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2016, 9, 19), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2016, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2016, 10, 10), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2016, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2016, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2016, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2017, 1, 2), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 9), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2017, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2017, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2017, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2017, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2017, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2017, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2017, 7, 17), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2017, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2017, 9, 18), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2017, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2017, 10, 9), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2017, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2017, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2017, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2018, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 1, 8), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2018, 2, 12), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2018, 3, 21), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2018, 4, 30), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2018, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2018, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2018, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2018, 7, 16), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2018, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2018, 9, 17), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2018, 9, 24), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2018, 10, 8), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2018, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2018, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2018, 12, 24), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2019, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 1, 14), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2019, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2019, 3, 21), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2019, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2019, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2019, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2019, 5, 6), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2019, 7, 15), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2019, 8, 12), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2019, 9, 16), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2019, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2019, 10, 14), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2019, 11, 4), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2019, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2019, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2020, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 13), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2020, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2020, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2020, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2020, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2020, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2020, 5, 6), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2020, 7, 20), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2020, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2020, 9, 21), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2020, 9, 22), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2020, 10, 12), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2020, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2020, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2020, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2021, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 1, 11), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2021, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2021, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2021, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2021, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2021, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2021, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2021, 7, 19), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2021, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2021, 9, 20), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2021, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2021, 10, 11), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2021, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2021, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2021, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2022, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 10), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2022, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2022, 3, 21), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2022, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2022, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2022, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2022, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2022, 7, 18), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2022, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2022, 9, 19), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2022, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2022, 10, 10), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2022, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2022, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2022, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2023, 1, 2), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 9), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2023, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2023, 3, 21), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2023, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2023, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2023, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2023, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2023, 7, 17), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2023, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2023, 9, 18), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2023, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2023, 10, 9), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2023, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2023, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2023, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2024, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 1, 8), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2024, 2, 12), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2024, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2024, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2024, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2024, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2024, 5, 6), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2024, 7, 15), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2024, 8, 12), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2024, 9, 16), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2024, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2024, 10, 14), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2024, 11, 4), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2024, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2024, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2025, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 13), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2025, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2025, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2025, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2025, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2025, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2025, 5, 6), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2025, 7, 21), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2025, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2025, 9, 15), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2025, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2025, 10, 13), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2025, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2025, 11, 24), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2025, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2026, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 1, 12), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2026, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2026, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2026, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2026, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2026, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2026, 5, 6), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2026, 7, 20), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2026, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2026, 9, 21), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2026, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2026, 10, 12), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2026, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2026, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2026, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2027, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 1, 11), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2027, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2027, 3, 22), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2027, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2027, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2027, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2027, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2027, 7, 19), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2027, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2027, 9, 20), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2027, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2027, 10, 11), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2027, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2027, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2027, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2028, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 10), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2028, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2028, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2028, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2028, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2028, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2028, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2028, 7, 17), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2028, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2028, 9, 18), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2028, 9, 22), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2028, 10, 9), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2028, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2028, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2028, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2029, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 1, 8), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2029, 2, 12), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2029, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2029, 4, 30), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2029, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2029, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2029, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2029, 7, 16), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2029, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2029, 9, 17), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2029, 9, 24), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2029, 10, 8), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2029, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2029, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2029, 12, 24), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2030, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 1, 14), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2030, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2030, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2030, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2030, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2030, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2030, 5, 6), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2030, 7, 15), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2030, 8, 12), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2030, 9, 16), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2030, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2030, 10, 14), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2030, 11, 4), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2030, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2030, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2031, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 13), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2031, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2031, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2031, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2031, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2031, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2031, 5, 6), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2031, 7, 21), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2031, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2031, 9, 15), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2031, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2031, 10, 13), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2031, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2031, 11, 24), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2031, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2032, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 1, 12), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2032, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2032, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2032, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2032, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2032, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2032, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2032, 7, 19), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2032, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2032, 9, 20), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2032, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2032, 10, 11), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2032, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2032, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2032, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2033, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 10), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2033, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2033, 3, 21), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2033, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2033, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2033, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2033, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2033, 7, 18), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2033, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2033, 9, 19), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2033, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2033, 10, 10), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2033, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2033, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2033, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2034, 1, 2), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 9), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2034, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2034, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2034, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2034, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2034, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2034, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2034, 7, 17), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2034, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2034, 9, 18), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2034, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2034, 10, 9), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2034, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2034, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2034, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2035, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 1, 8), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2035, 2, 12), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2035, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2035, 4, 30), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2035, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2035, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2035, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2035, 7, 16), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2035, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2035, 9, 17), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2035, 9, 24), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2035, 10, 8), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2035, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2035, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2035, 12, 24), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2036, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 14), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2036, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2036, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2036, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2036, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2036, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2036, 5, 6), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2036, 7, 21), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2036, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2036, 9, 15), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2036, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2036, 10, 13), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2036, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2036, 11, 24), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2036, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2037, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 1, 12), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2037, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2037, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2037, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2037, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2037, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2037, 5, 6), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2037, 7, 20), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2037, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2037, 9, 21), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2037, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2037, 10, 12), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2037, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2037, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2037, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2038, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 1, 11), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2038, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2038, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2038, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2038, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2038, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2038, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2038, 7, 19), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2038, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2038, 9, 20), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2038, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2038, 10, 11), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2038, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2038, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2038, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2039, 1, 1), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 10), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2039, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2039, 3, 21), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2039, 4, 29), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2039, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2039, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2039, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2039, 7, 18), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2039, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2039, 9, 19), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2039, 9, 23), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2039, 10, 10), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2039, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2039, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2039, 12, 23), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday"),
          NationalHoliday.new(Date.new(2040, 1, 2), "元日 Ganjitsu", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 1, 9), "成人の日 Seijin no Hi", "Coming of Age Day"),
          NationalHoliday.new(Date.new(2040, 2, 11), "建国記念の日 Kenkoku Kinen no Hi", "Foundation Day"),
          NationalHoliday.new(Date.new(2040, 3, 20), "春分の日 Shunbun no Hi", "Vernal Equinox Day"),
          NationalHoliday.new(Date.new(2040, 4, 30), "昭和の日 Shōwa no Hi", "Shōwa Day"),
          NationalHoliday.new(Date.new(2040, 5, 3), "憲法記念日 Kenpō Kinenbi", "Constitution Memorial Day"),
          NationalHoliday.new(Date.new(2040, 5, 4), "みどりの日 Midori no Hi", "Greenery Day"),
          NationalHoliday.new(Date.new(2040, 5, 5), "こどもの日 Kodomo no Hi", "Children's Day"),
          NationalHoliday.new(Date.new(2040, 7, 16), "海の日 Umi no Hi", "Marine Day"),
          NationalHoliday.new(Date.new(2040, 8, 11), "山の日 Yama no Hi", "Mountain Day"),
          NationalHoliday.new(Date.new(2040, 9, 17), "敬老の日 Keirō no Hi", "Respect-for-the-Aged Day"),
          NationalHoliday.new(Date.new(2040, 9, 24), "秋分の日 Shūbun no Hi", "Autumnal Equinox Day"),
          NationalHoliday.new(Date.new(2040, 10, 8), "体育の日 Taiiku no Hi", "Health and Sports Day"),
          NationalHoliday.new(Date.new(2040, 11, 3), "文化の日 Bunka no Hi", "Culture Day"),
          NationalHoliday.new(Date.new(2040, 11, 23), "勤労感謝の日 Kinrō Kansha no Hi", "Labour Thanksgiving Day"),
          NationalHoliday.new(Date.new(2040, 12, 24), "天皇誕生日 Tennō Tanjōbi", "The Emperor's Birthday")
        ]
      end

    end
  end
end
