module NationalHolidays
  module Countries
    class Latvia < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Latvia (all)', 'latvia01', self.riga) ]
      end

      def riga
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 4, 22), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2011, 4, 24), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2011, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2011, 5, 8), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2011, 6, 12), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2011, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2011, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2011, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2011, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2011, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2011, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 4, 6), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2012, 4, 8), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 4, 30), "Darba svētkus", "Labour Day Holiday"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2012, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2012, 5, 13), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2012, 5, 27), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2012, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2012, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2012, 11, 19), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2012, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2012, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 3, 29), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2013, 3, 31), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2013, 5, 6), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2013, 5, 12), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2013, 5, 19), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2013, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2013, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2013, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2013, 12, 23), "Ziemassvētku vakars", "Christmas Bridge Holiday"),
          NationalHoliday.new(Date.new(2013, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2013, 12, 30), "Vecgada vakars", "New Year's Bridge Holiday"),
          NationalHoliday.new(Date.new(2013, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 4, 18), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2014, 5, 2), "Darba svētkus", "Labour Day Bridge Holiday"),
          NationalHoliday.new(Date.new(2014, 5, 5), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2014, 5, 11), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2014, 6, 8), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2014, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2014, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2014, 11, 17), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia Bridge Holiday"),
          NationalHoliday.new(Date.new(2014, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2014, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2014, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 2), "Jaungada dienu", "New Year's Day Bridge Holiday"),
          NationalHoliday.new(Date.new(2015, 4, 3), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2015, 4, 5), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2015, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2015, 5, 10), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2015, 5, 24), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2015, 6, 22), "Līgo dienu", "Midsummer Bridge Holiday"),
          NationalHoliday.new(Date.new(2015, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2015, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2015, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2015, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2015, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 3, 25), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2016, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2016, 5, 8), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2016, 5, 15), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2016, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2016, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2016, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2016, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2016, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2017, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2017, 5, 14), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2017, 6, 4), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2017, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2017, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2017, 11, 20), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2017, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2017, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 3, 30), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2018, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2018, 5, 13), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2018, 5, 20), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2018, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2018, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2018, 11, 19), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2018, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2018, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 4, 19), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2019, 5, 6), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2019, 5, 12), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2019, 6, 9), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2019, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2019, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2019, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2019, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2019, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 4, 10), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2020, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2020, 5, 10), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2020, 5, 31), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2020, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2020, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2020, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2020, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2020, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 4, 2), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2021, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2021, 5, 9), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2021, 5, 23), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2021, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2021, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2021, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2021, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2021, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 4, 15), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2022, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2022, 5, 8), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2022, 6, 5), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2022, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2022, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2022, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2022, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2022, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 4, 7), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2023, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2023, 5, 14), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2023, 5, 28), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2023, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2023, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2023, 11, 20), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2023, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2023, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 3, 29), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2024, 5, 6), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2024, 5, 12), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2024, 5, 19), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2024, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2024, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2024, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2024, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2024, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2025, 5, 5), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2025, 5, 11), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2025, 6, 8), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2025, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2025, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2025, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2025, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2025, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 4, 3), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2026, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2026, 5, 10), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2026, 5, 24), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2026, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2026, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2026, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2026, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2026, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 3, 26), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2027, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2027, 5, 9), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2027, 5, 16), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2027, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2027, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2027, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2027, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2027, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2028, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2028, 5, 14), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2028, 6, 4), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2028, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2028, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2028, 11, 20), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2028, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2028, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 3, 30), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2029, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2029, 5, 13), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2029, 5, 20), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2029, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2029, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2029, 11, 19), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2029, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2029, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 4, 19), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2030, 5, 6), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2030, 5, 12), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2030, 6, 9), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2030, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2030, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2030, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2030, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2030, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2031, 5, 5), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2031, 5, 11), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2031, 6, 1), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2031, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2031, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2031, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2031, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2031, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 3, 26), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2032, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2032, 5, 9), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2032, 5, 16), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2032, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2032, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2032, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2032, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2032, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 4, 15), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2033, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2033, 5, 8), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2033, 6, 5), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2033, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2033, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2033, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2033, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2033, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2034, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2034, 5, 14), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2034, 5, 28), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2034, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2034, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2034, 11, 20), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2034, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2034, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 3, 23), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2035, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2035, 5, 13), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2035, 5, 13), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2035, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2035, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2035, 11, 19), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2035, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2035, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 4, 11), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2036, 5, 5), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2036, 5, 11), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2036, 6, 1), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2036, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2036, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2036, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2036, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2036, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2037, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2037, 5, 10), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2037, 5, 24), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2037, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2037, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2037, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2037, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2037, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2038, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2038, 5, 9), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2038, 6, 13), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2038, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2038, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2038, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2038, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2038, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 4, 8), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2039, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2039, 5, 8), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2039, 5, 29), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2039, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2039, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2039, 11, 18), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2039, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2039, 12, 31), "Vecgada vakars", "New Year's Eve"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Jaungada dienu", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 3, 30), "Lielo Piektdienu", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Pirmās Lieldienas", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Otro Lieldienu dienu", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Darba svētkus", "Labour Day"),
          NationalHoliday.new(Date.new(2040, 5, 4), "Latvijas Republikas Neatkarības atjaunošanas dienu", "Restoration of Independence day"),
          NationalHoliday.new(Date.new(2040, 5, 13), "Mātes diena", "Mother's day"),
          NationalHoliday.new(Date.new(2040, 5, 20), "Vasarsvētkus", "Whit Sunday"),
          NationalHoliday.new(Date.new(2040, 6, 23), "Līgo dienu", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2040, 6, 24), "Jāņu dienu", "Midsummer"),
          NationalHoliday.new(Date.new(2040, 11, 19), "Latvijas Republikas proklamēšanas diena", "Proclamation of the Republic of Latvia"),
          NationalHoliday.new(Date.new(2040, 12, 24), "Ziemassvētku vakars", "Christmas Eve"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Ziemassvētki", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "2. Ziemassvētki", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2040, 12, 31), "Vecgada vakars", "New Year's Eve")
        ]
      end

    end
  end
end
