module NationalHolidays
  module Countries
    class Lithuania < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Lithuania (all)', 'lithuania01', self.vilnius) ]
      end

      def vilnius
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2011, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2011, 4, 24), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2011, 6, 5), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2011, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2011, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2011, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2011, 10, 31), "Visų šventųjų atostogų", "All Saints' Holiday"),
          NationalHoliday.new(Date.new(2011, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2011, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2011, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2012, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2012, 4, 8), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2012, 5, 6), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2012, 6, 3), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2012, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2012, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2012, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2012, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2012, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2013, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2013, 3, 31), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2013, 5, 5), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2013, 6, 2), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2013, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2013, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2013, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2013, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2013, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2014, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2014, 5, 4), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2014, 6, 1), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2014, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2014, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2014, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2014, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2014, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2015, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2015, 4, 5), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2015, 5, 3), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2015, 6, 7), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2015, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2015, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2015, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2015, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2015, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2016, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2016, 6, 5), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2016, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2016, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2016, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2016, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2016, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2017, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2017, 5, 7), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2017, 6, 4), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2017, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2017, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2017, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2017, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2017, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2018, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2018, 5, 6), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2018, 6, 3), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2018, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2018, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2018, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2018, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2018, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2019, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2019, 5, 5), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2019, 6, 2), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2019, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2019, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2019, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2019, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2019, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2020, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2020, 5, 3), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2020, 6, 7), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2020, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2020, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2020, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2020, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2020, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2021, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2021, 5, 2), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2021, 6, 6), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2021, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2021, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2021, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2021, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2021, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2022, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2022, 6, 5), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2022, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2022, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2022, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2022, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2022, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2023, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2023, 5, 7), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2023, 6, 4), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2023, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2023, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2023, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2023, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2023, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2024, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2024, 5, 5), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2024, 6, 2), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2024, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2024, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2024, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2024, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2024, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2025, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2025, 5, 4), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2025, 6, 1), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2025, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2025, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2025, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2025, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2025, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2026, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2026, 5, 3), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2026, 6, 7), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2026, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2026, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2026, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2026, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2026, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2027, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2027, 5, 2), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2027, 6, 6), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2027, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2027, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2027, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2027, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2027, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2028, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2028, 5, 7), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2028, 6, 4), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2028, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2028, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2028, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2028, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2028, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2029, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2029, 5, 6), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2029, 6, 3), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2029, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2029, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2029, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2029, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2029, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2030, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2030, 5, 5), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2030, 6, 2), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2030, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2030, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2030, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2030, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2030, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2031, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2031, 5, 4), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2031, 6, 1), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2031, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2031, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2031, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2031, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2031, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2032, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2032, 5, 2), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2032, 6, 6), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2032, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2032, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2032, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2032, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2032, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2033, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2033, 6, 5), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2033, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2033, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2033, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2033, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2033, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2034, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2034, 5, 7), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2034, 6, 4), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2034, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2034, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2034, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2034, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2034, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2035, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2035, 5, 6), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2035, 6, 3), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2035, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2035, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2035, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2035, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2035, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2036, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2036, 5, 4), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2036, 6, 1), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2036, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2036, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2036, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2036, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2036, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2037, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2037, 5, 3), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2037, 6, 7), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2037, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2037, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2037, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2037, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2037, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2038, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2038, 5, 2), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2038, 6, 6), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2038, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2038, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2038, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2038, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2038, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2039, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2039, 6, 5), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2039, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2039, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2039, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2039, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2039, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Šv. Kalėdos", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Naujieji metai", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 2, 16), "Lietuvos valstybės atkūrimo diena", "Day of Re-establishment of the State of Lithuania (1918)"),
          NationalHoliday.new(Date.new(2040, 3, 11), "Lietuvos nepriklausomybės atkūrimo diena", "Day of Restitution of Independence of Lithuania (from the Soviet Union, 1990)"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Velykos", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Velykos", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Tarptautinė darbo diena", "Labour Day"),
          NationalHoliday.new(Date.new(2040, 5, 6), "Motinos diena", "Mother's day"),
          NationalHoliday.new(Date.new(2040, 6, 3), "Tėvo diena", "Father's Day"),
          NationalHoliday.new(Date.new(2040, 6, 24), "Rasos (Joninės)", "St. John's Day (Day of Dew)"),
          NationalHoliday.new(Date.new(2040, 7, 6), "Valstybės (Lietuvos karaliaus Mindaugo karūnavimo) diena", "Statehood Day"),
          NationalHoliday.new(Date.new(2040, 8, 15), "Žolinė (Švč. Mergelės Marijos ėmimo į dangų diena)", "Assumption Day"),
          NationalHoliday.new(Date.new(2040, 11, 1), "Visų šventųjų diena", "All Saints' Day"),
          NationalHoliday.new(Date.new(2040, 12, 24), "Šv. Kalėdos", "Christmas Eve"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Šv. Kalėdos", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Šv. Kalėdos", "St. Stephen's Day")
        ]
      end

    end
  end
end
