module NationalHolidays
  module Countries
    class Mexico < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Mexico (all)', 'mexico01', self.mexico_city) ]
      end

      def mexico_city
        [
          NationalHoliday.new(Date.new(2014, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 2, 3), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2014, 3, 17), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2014, 4, 17), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2014, 4, 18), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2014, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2014, 11, 17), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 2, 2), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2015, 3, 16), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2015, 4, 2), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2015, 4, 3), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2015, 4, 5), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2015, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2015, 11, 16), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 2, 1), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2016, 3, 21), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2016, 3, 24), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2016, 3, 25), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2016, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2016, 11, 21), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 2, 6), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2017, 3, 20), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2017, 4, 13), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2017, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2017, 11, 20), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 2, 5), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2018, 3, 19), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2018, 3, 29), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2018, 3, 30), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2018, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2018, 11, 19), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2018, 12, 1), "Transmisión del Poder Ejecutivo Federal", "Change of Federal Government"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 2, 4), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2019, 3, 18), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2019, 4, 18), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2019, 4, 19), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2019, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2019, 11, 18), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 2, 3), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2020, 3, 16), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2020, 4, 9), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2020, 4, 10), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2020, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2020, 11, 16), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 2, 1), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2021, 3, 15), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2021, 4, 1), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2021, 4, 2), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2021, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2021, 11, 15), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 2, 7), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2022, 3, 21), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2022, 4, 14), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2022, 4, 15), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2022, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2022, 11, 21), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 2, 6), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2023, 3, 20), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2023, 4, 6), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2023, 4, 7), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2023, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2023, 11, 20), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 2, 5), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2024, 3, 18), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2024, 3, 28), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2024, 3, 29), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2024, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2024, 11, 18), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2024, 12, 1), "Transmisión del Poder Ejecutivo Federal", "Change of Federal Government"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 2, 3), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2025, 3, 17), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2025, 4, 17), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2025, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2025, 11, 17), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 2, 2), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2026, 3, 16), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2026, 4, 2), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2026, 4, 3), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2026, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2026, 11, 16), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 2, 1), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2027, 3, 15), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2027, 3, 25), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2027, 3, 26), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2027, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2027, 11, 15), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 2, 7), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2028, 3, 20), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2028, 4, 13), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2028, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2028, 11, 20), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 2, 5), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2029, 3, 19), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2029, 3, 29), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2029, 3, 30), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2029, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2029, 11, 19), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 2, 4), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2030, 3, 18), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2030, 4, 18), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2030, 4, 19), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2030, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2030, 11, 18), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2030, 12, 1), "Transmisión del Poder Ejecutivo Federal", "Change of Federal Government"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 2, 3), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2031, 3, 17), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2031, 4, 10), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2031, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2031, 11, 17), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 2, 2), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2032, 3, 15), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2032, 3, 25), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2032, 3, 26), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2032, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2032, 11, 15), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 2, 7), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2033, 3, 21), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2033, 4, 14), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2033, 4, 15), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2033, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2033, 11, 21), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 2, 6), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2034, 3, 20), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2034, 4, 6), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2034, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2034, 11, 20), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 2, 5), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2035, 3, 19), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2035, 3, 22), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2035, 3, 23), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2035, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2035, 11, 19), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 2, 4), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2036, 3, 17), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2036, 4, 10), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2036, 4, 11), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2036, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2036, 11, 17), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2036, 12, 1), "Transmisión del Poder Ejecutivo Federal", "Change of Federal Government"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 2, 2), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2037, 3, 16), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2037, 4, 2), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2037, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2037, 11, 16), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 2, 1), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2038, 3, 15), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2038, 4, 22), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2038, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2038, 11, 15), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 2, 7), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2039, 3, 21), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2039, 4, 7), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2039, 4, 8), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2039, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2039, 11, 21), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Día de Navidad", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Año Nuevo", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 2, 6), "Día de la Constitución Mexicana", "Constitution Day"),
          NationalHoliday.new(Date.new(2040, 3, 19), "Natalicio de Benito Juárez", "Benito Juárez's Birthday"),
          NationalHoliday.new(Date.new(2040, 3, 29), "Jueves Santo", "Maundy Thursday"),
          NationalHoliday.new(Date.new(2040, 3, 30), "Viernes Santo", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Domingo de Resurrección", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Día del Trabajo", "Labor Day"),
          NationalHoliday.new(Date.new(2040, 9, 16), "Día de la Independencia", "Independence Day"),
          NationalHoliday.new(Date.new(2040, 11, 19), "Revolución Mexicana", "Revolution Day"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Día de Navidad", "Christmas Day")
        ]
      end

    end
  end
end
