module NationalHolidays
  module Countries
    class Netherlands < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Netherlands (all)', 'netherlands01', self.north_holland) ]
      end

      def north_holland
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 4, 24), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 4, 30), "Koninginnedag", "Queen's Day"),
          NationalHoliday.new(Date.new(2011, 6, 2), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2011, 6, 12), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2011, 6, 13), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2011, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 4, 8), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 4, 30), "Koninginnedag", "Queen's Day"),
          NationalHoliday.new(Date.new(2012, 5, 17), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2012, 5, 27), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2012, 5, 28), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 3, 31), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 4, 30), "Koninginnedag", "Queen's Day"),
          NationalHoliday.new(Date.new(2013, 5, 9), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2013, 5, 19), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2013, 5, 20), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 4, 26), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2014, 5, 29), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2014, 6, 8), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2014, 6, 9), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 4, 5), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2015, 5, 5), "Bevrijdingsdag", "Liberation Day"),
          NationalHoliday.new(Date.new(2015, 5, 14), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2015, 5, 24), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2015, 5, 25), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2016, 5, 5), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2016, 5, 15), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2016, 5, 16), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2017, 5, 25), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2017, 6, 4), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2017, 6, 5), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2018, 5, 10), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2018, 5, 20), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2018, 5, 21), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2019, 5, 30), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2019, 6, 9), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2019, 6, 10), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2020, 5, 5), "Bevrijdingsdag", "Liberation Day"),
          NationalHoliday.new(Date.new(2020, 5, 21), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2020, 5, 31), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2020, 6, 1), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2021, 5, 13), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2021, 5, 23), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2021, 5, 24), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2022, 5, 26), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2022, 6, 5), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2022, 6, 6), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2023, 5, 18), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2023, 5, 28), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2023, 5, 29), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2024, 5, 9), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2024, 5, 19), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2024, 5, 20), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 4, 26), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2025, 5, 5), "Bevrijdingsdag", "Liberation Day"),
          NationalHoliday.new(Date.new(2025, 5, 29), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2025, 6, 8), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2025, 6, 9), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2026, 5, 14), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2026, 5, 24), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2026, 5, 25), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2027, 5, 6), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2027, 5, 16), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2027, 5, 17), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2028, 5, 25), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2028, 6, 4), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2028, 6, 5), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2029, 5, 10), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2029, 5, 20), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2029, 5, 21), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2030, 5, 5), "Bevrijdingsdag", "Liberation Day"),
          NationalHoliday.new(Date.new(2030, 5, 30), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2030, 6, 9), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2030, 6, 10), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 4, 26), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2031, 5, 22), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2031, 6, 1), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2031, 6, 2), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2032, 5, 6), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2032, 5, 16), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2032, 5, 17), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2033, 5, 26), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2033, 6, 5), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2033, 6, 6), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2034, 5, 18), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2034, 5, 28), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2034, 5, 29), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2035, 5, 3), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2035, 5, 5), "Bevrijdingsdag", "Liberation Day"),
          NationalHoliday.new(Date.new(2035, 5, 13), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2035, 5, 14), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 4, 26), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2036, 5, 22), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2036, 6, 1), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2036, 6, 2), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2037, 5, 14), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2037, 5, 24), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2037, 5, 25), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2038, 6, 3), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2038, 6, 13), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2038, 6, 14), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2039, 5, 19), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2039, 5, 29), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2039, 5, 30), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Tweede Kerstdag", "Boxing Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Nieuwjaar", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Eerste Paasdag", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Tweede Paasdag", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 4, 27), "Koningsdag", "King's Day"),
          NationalHoliday.new(Date.new(2040, 5, 5), "Bevrijdingsdag", "Liberation Day"),
          NationalHoliday.new(Date.new(2040, 5, 10), "	Hemelvaartsdag", "Ascension Day"),
          NationalHoliday.new(Date.new(2040, 5, 20), "Eerste Pinksterdag", "Whit Sunday"),
          NationalHoliday.new(Date.new(2040, 5, 21), "Tweede Pinksterdag", "Whit Monday"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Eerste Kerstdag", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Tweede Kerstdag", "Boxing Day")
        ]
      end

    end
  end
end
