module NationalHolidays
  module Countries
    class Poland < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Poland (all)', 'poland01', self.krakow) ]
      end

      def krakow
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2011, 4, 24), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2011, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2011, 6, 12), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2011, 6, 23), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2011, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2011, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2011, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2011, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2012, 4, 8), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2012, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2012, 5, 27), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2012, 6, 7), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2012, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2012, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2012, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2013, 3, 31), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2013, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2013, 5, 19), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2013, 5, 30), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2013, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2013, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2013, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2014, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2014, 6, 8), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2014, 6, 19), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2014, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2014, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2014, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2015, 4, 5), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2015, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2015, 5, 24), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2015, 6, 4), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2015, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2015, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2015, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2016, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2016, 5, 15), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2016, 5, 26), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2016, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2016, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2016, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2017, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2017, 6, 4), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2017, 6, 15), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2017, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2017, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2017, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2018, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2018, 5, 20), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2018, 5, 31), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2018, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2018, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2018, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2019, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2019, 6, 9), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2019, 6, 20), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2019, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2019, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2019, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2020, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2020, 5, 31), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2020, 6, 11), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2020, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2020, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2020, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2021, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2021, 5, 23), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2021, 6, 3), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2021, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2021, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2021, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2022, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2022, 6, 5), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2022, 6, 16), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2022, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2022, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2022, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2023, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2023, 5, 28), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2023, 6, 8), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2023, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2023, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2023, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2024, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2024, 5, 19), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2024, 5, 30), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2024, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2024, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2024, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2025, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2025, 6, 8), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2025, 6, 19), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2025, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2025, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2025, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2026, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2026, 5, 24), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2026, 6, 4), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2026, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2026, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2026, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2027, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2027, 5, 16), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2027, 5, 27), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2027, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2027, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2027, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2028, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2028, 6, 4), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2028, 6, 15), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2028, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2028, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2028, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2029, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2029, 5, 20), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2029, 5, 31), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2029, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2029, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2029, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2030, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2030, 6, 9), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2030, 6, 20), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2030, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2030, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2030, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2031, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2031, 6, 1), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2031, 6, 12), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2031, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2031, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2031, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2032, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2032, 5, 16), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2032, 5, 27), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2032, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2032, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2032, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2033, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2033, 6, 5), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2033, 6, 16), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2033, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2033, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2033, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2034, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2034, 5, 28), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2034, 6, 8), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2034, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2034, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2034, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2035, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2035, 5, 13), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2035, 5, 24), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2035, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2035, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2035, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2036, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2036, 6, 1), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2036, 6, 12), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2036, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2036, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2036, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2037, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2037, 5, 24), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2037, 6, 4), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2037, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2037, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2037, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2038, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2038, 6, 13), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2038, 6, 24), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2038, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2038, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2038, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2039, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2039, 5, 29), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2039, 6, 9), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2039, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2039, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2039, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Nowy Rok", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 1, 6), "Święto Trzech Króli", "Epiphany"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Wielkanoc", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Poniedziałek Wielkanocny", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Święto Pracy", "Labour Day"),
          NationalHoliday.new(Date.new(2040, 5, 3), "Święto Konstytucji 3 Maja", "Constitution Day"),
          NationalHoliday.new(Date.new(2040, 5, 20), "Zielone Świątki", "Whit Sunday"),
          NationalHoliday.new(Date.new(2040, 5, 31), "Boże Ciało", "Corpus Christi"),
          NationalHoliday.new(Date.new(2040, 8, 15), "Wniebowzięcie Najświętszej Maryi Panny", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2040, 11, 1), "Wszystkich Świętych", "All Saints' Day"),
          NationalHoliday.new(Date.new(2040, 11, 11), "Narodowe Święto Niepodległości", "Independence Day"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Boże Narodzenie", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Drugi dzień Bożego Narodzenia", "Second day of Christmas")
        ]
      end

    end
  end
end
