module NationalHolidays
  module Countries
    class Romania < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Romania (all)', 'romania01', self.bucharest) ]
      end

      def bucharest
        [
          NationalHoliday.new(Date.new(2015, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2015, 4, 12), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 13), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2015, 5, 31), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2015, 6, 1), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2015, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2015, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2015, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2016, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2016, 5, 2), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2016, 6, 19), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2016, 6, 20), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2016, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2016, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2016, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2017, 6, 4), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2017, 6, 5), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2017, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2017, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2017, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2018, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2018, 4, 8), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 9), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2018, 5, 27), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2018, 5, 28), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2018, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2018, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2018, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2019, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2019, 4, 28), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 29), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2019, 6, 16), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2019, 6, 17), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2019, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2019, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2019, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2020, 4, 19), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 20), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2020, 6, 7), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2020, 6, 8), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2020, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2020, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2020, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2021, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2021, 5, 2), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 5, 3), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2021, 6, 20), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2021, 6, 21), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2021, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2021, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2021, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2022, 4, 24), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 25), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2022, 6, 12), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2022, 6, 13), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2022, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2022, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2022, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2023, 4, 16), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 17), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2023, 6, 4), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2023, 6, 5), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2023, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2023, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2023, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2024, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2024, 5, 5), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 5, 6), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2024, 6, 23), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2024, 6, 24), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2024, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2024, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2024, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2025, 6, 8), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2025, 6, 9), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2025, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2025, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2025, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2026, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2026, 4, 12), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 13), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2026, 5, 31), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2026, 6, 1), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2026, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2026, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2026, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2027, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2027, 5, 2), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 5, 3), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2027, 6, 20), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2027, 6, 21), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2027, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2027, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2027, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2028, 6, 4), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2028, 6, 5), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2028, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2028, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2028, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2029, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2029, 4, 8), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 9), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2029, 5, 27), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2029, 5, 28), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2029, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2029, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2029, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2030, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2030, 4, 28), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 29), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2030, 6, 16), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2030, 6, 17), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2030, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2030, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2030, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2031, 6, 1), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2031, 6, 2), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2031, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2031, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2031, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2032, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2032, 5, 2), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 5, 3), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2032, 6, 20), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2032, 6, 21), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2032, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2032, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2032, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2033, 4, 24), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 25), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2033, 6, 12), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2033, 6, 13), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2033, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2033, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2033, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2034, 5, 28), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2034, 5, 29), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2034, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2034, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2034, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2035, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2035, 4, 29), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 4, 30), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2035, 6, 17), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2035, 6, 18), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2035, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2035, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2035, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2036, 4, 20), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 21), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2036, 6, 8), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2036, 6, 9), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2036, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2036, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2036, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2037, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2037, 5, 24), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2037, 5, 25), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2037, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2037, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2037, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2038, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2038, 6, 13), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2038, 6, 14), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2038, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2038, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2038, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2039, 4, 17), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 18), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2039, 6, 5), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2039, 6, 6), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2039, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2039, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2039, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Crăciunul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Anul nou", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 1, 2), "Anul nou", "Day after New Year's Day"),
          NationalHoliday.new(Date.new(2040, 1, 24), "Unirea Principatelor Române/Mica Unire", "Unification of the Romanian Principalities/Small Union"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Ziua muncii", "Labour Day"),
          NationalHoliday.new(Date.new(2040, 5, 6), "Paştele", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 5, 7), "Doua zi de Pasti", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2040, 6, 24), "Rusaliile", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2040, 6, 25), "Doua zi de Rusaliile", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2040, 8, 15), "Adormirea Maicii Domnului/Sfânta Maria Mare", "Dormition of the Theotokos"),
          NationalHoliday.new(Date.new(2040, 11, 30), "Sfântul Andrei", "St. Andrew's Day"),
          NationalHoliday.new(Date.new(2040, 12, 1), "Ziua Națională/Marea Unire", "National Day/Great Union"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Crăciunul", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Crăciunul", "St Stephen's Day")
        ]
      end

    end
  end
end
