module NationalHolidays
  module Countries
    class Russia < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Russia (all)', 'russia01', self.moscow) ]
      end

      def moscow
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2011, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2011, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2011, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2011, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2011, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2011, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2011, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2011, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2011, 1, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2011, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2011, 3, 7), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2011, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2011, 5, 2), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2011, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2011, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2011, 6, 13), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2011, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2012, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2012, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2012, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2012, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2012, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2012, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2012, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2012, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2012, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2012, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2012, 3, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2012, 4, 30), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2012, 5, 7), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2012, 5, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2012, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2012, 6, 11), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2012, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2012, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2012, 11, 5), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2012, 12, 31), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2013, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2013, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2013, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2013, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2013, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2013, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2013, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2013, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2013, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2013, 5, 2), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2013, 5, 3), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2013, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2013, 5, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2013, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2013, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2014, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2014, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2014, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2014, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2014, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2014, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2014, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2014, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2014, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2014, 3, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2014, 5, 2), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2014, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2014, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2014, 6, 13), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2014, 11, 3), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2014, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2015, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2015, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2015, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2015, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2015, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2015, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2015, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2015, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2015, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2015, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2015, 3, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2015, 5, 4), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2015, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2015, 5, 11), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2015, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2015, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2016, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2016, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2016, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2016, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2016, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2016, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2016, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2016, 2, 22), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2016, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2016, 3, 7), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2016, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2016, 5, 2), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2016, 5, 3), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2016, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2016, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2016, 6, 13), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2016, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2017, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2017, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2017, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2017, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2017, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2017, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2017, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2017, 11, 6), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2018, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2018, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2018, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2018, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2018, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2018, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2018, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2018, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2018, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2018, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2018, 4, 30), "Праздник", "Spring and Labour Day Holiday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2018, 5, 2), "Праздник", "Spring and Labour Day Holiday"),
          NationalHoliday.new(Date.new(2018, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2018, 6, 11), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2018, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2018, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2018, 11, 5), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2019, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2019, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2019, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2019, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2019, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2019, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2019, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2019, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2019, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2019, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2019, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2019, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2020, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2020, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2020, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2020, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2020, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2020, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2020, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2020, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2020, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2020, 3, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2020, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2020, 5, 11), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2020, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2020, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2021, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2021, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2021, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2021, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2021, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2021, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2021, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2021, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2021, 1, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2021, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2021, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2021, 5, 3), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2021, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2021, 5, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2021, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2021, 6, 14), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2021, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2022, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2022, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2022, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2022, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2022, 5, 2), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2022, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2022, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2022, 6, 13), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2022, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2023, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2023, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2023, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2023, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2023, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2023, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2023, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2023, 11, 6), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2024, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2024, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2024, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2024, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2024, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2024, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2024, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2024, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2024, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2024, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2024, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2024, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2024, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2025, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2025, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2025, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2025, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2025, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2025, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2025, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2025, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2025, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2025, 3, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2025, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2025, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2025, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2026, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2026, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2026, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2026, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2026, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2026, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2026, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2026, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2026, 1, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2026, 1, 11), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2026, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2026, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2026, 3, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2026, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2026, 5, 11), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2026, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2026, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2027, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2027, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2027, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2027, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2027, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2027, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2027, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2027, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2027, 1, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2027, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2027, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2027, 5, 3), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2027, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2027, 5, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2027, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2027, 6, 14), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2027, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2028, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2028, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2028, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2028, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2028, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2028, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2028, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2028, 11, 6), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2029, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2029, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2029, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2029, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2029, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2029, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2029, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2029, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2029, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2029, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2029, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2029, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2029, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2029, 11, 5), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2030, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2030, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2030, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2030, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2030, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2030, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2030, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2030, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2030, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2030, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2030, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2030, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2031, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2031, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2031, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2031, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2031, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2031, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2031, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2031, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2031, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2031, 3, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2031, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2031, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2031, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2032, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2032, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2032, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2032, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2032, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2032, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2032, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2032, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2032, 1, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2032, 1, 11), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2032, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2032, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2032, 5, 3), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2032, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2032, 5, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2032, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2032, 6, 14), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2032, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2033, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2033, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2033, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2033, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2033, 5, 2), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2033, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2033, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2033, 6, 13), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2033, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2034, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2034, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2034, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2034, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2034, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2034, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2034, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2034, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2034, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2034, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2034, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2034, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2034, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2034, 11, 6), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2035, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2035, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2035, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2035, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2035, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2035, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2035, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2035, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2035, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2035, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2035, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2035, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2035, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2035, 11, 5), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2036, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2036, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2036, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2036, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2036, 3, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2036, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2036, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2036, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2037, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2037, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2037, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2037, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2037, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2037, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2037, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2037, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2037, 1, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2037, 1, 11), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2037, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2037, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2037, 3, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2037, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2037, 5, 11), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2037, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2037, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2038, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2038, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2038, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2038, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2038, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2038, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2038, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2038, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2038, 1, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2038, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2038, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2038, 5, 3), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2038, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2038, 5, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2038, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2038, 6, 14), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2038, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2039, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2039, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 10), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2039, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2039, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2039, 5, 2), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2039, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2039, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2039, 6, 13), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2039, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Новый год", "New Year’s Day"),
          NationalHoliday.new(Date.new(2040, 1, 2), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2040, 1, 3), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2040, 1, 4), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2040, 1, 5), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2040, 1, 6), "Новогодние каникулы", "New Year’s Holiday"),
          NationalHoliday.new(Date.new(2040, 1, 7), "Рождество Христово", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2040, 1, 8), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2040, 1, 9), "Праздник", "Holiday"),
          NationalHoliday.new(Date.new(2040, 2, 23), "День защитника Отечества", "Defender of the Fatherland Day"),
          NationalHoliday.new(Date.new(2040, 3, 8), "Восьмое марта", "International Women's Day"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Праздник Весны и Труда", "The Day of Spring and Labor"),
          NationalHoliday.new(Date.new(2040, 5, 9), "День Победы", "Victory Day"),
          NationalHoliday.new(Date.new(2040, 6, 12), "День России", "Russia Day"),
          NationalHoliday.new(Date.new(2040, 11, 4), "День народного единства", "Unity Day"),
          NationalHoliday.new(Date.new(2040, 11, 5), "Праздник", "Holiday")
        ]
      end

    end
  end
end
