module NationalHolidays
  module Countries
    class Serbia < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Serbia (all)', 'serbia01', self.belgrade) ]
      end

      def belgrade
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2011, 1, 3), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2011, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2011, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2011, 4, 22), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2011, 4, 24), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2011, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2011, 5, 3), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2012, 1, 3), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2012, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2012, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2012, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2012, 2, 17), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2012, 4, 13), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2012, 4, 15), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2012, 4, 16), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2012, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2012, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2012, 11, 12), "Dan primirja", "Armistice Day Holiday"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2013, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2013, 1, 14), "Srpska nova godina", "Orthodox New Year"),
          NationalHoliday.new(Date.new(2013, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2013, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2013, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2013, 5, 3), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2013, 5, 5), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2013, 5, 6), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2013, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2014, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2014, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2014, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2014, 2, 17), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2014, 4, 18), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2014, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2014, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2015, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2015, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2015, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2015, 2, 17), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2015, 4, 10), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2015, 4, 12), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2015, 4, 13), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2015, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2015, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2016, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2016, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2016, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2016, 4, 29), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2016, 5, 2), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2016, 5, 3), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2016, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 3), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2017, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2017, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2017, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2017, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2018, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2018, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2018, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2018, 4, 6), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 8), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2018, 4, 9), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2018, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2018, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2018, 11, 12), "Dan primirja", "Armistice Day Holiday"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2019, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2019, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2019, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2019, 4, 26), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 28), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2019, 4, 29), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2019, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2019, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2020, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2020, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2020, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2020, 2, 17), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2020, 4, 17), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 19), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2020, 4, 20), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2020, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2020, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2021, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2021, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2021, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2021, 4, 30), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2021, 5, 2), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2021, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2021, 5, 3), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 3), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2021, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 3), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2022, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2022, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2022, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2022, 4, 22), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 24), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2022, 4, 25), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2022, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2022, 5, 3), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2022, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 3), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2023, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2023, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2023, 4, 14), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 16), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2023, 4, 17), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2023, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2023, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2024, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2024, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2024, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2024, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2024, 5, 3), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2024, 5, 5), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2024, 5, 6), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2024, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2025, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2025, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2025, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2025, 2, 17), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2025, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2025, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2026, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2026, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2026, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2026, 2, 17), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2026, 4, 10), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 12), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2026, 4, 13), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2026, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2026, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2027, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2027, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2027, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2027, 4, 30), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2027, 5, 2), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2027, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2027, 5, 3), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 3), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2027, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 3), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2028, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2028, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2028, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2028, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2029, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2029, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2029, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2029, 4, 6), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 8), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2029, 4, 9), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2029, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2029, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2029, 11, 12), "Dan primirja", "Armistice Day Holiday"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2030, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2030, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2030, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2030, 4, 26), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 28), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2030, 4, 29), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2030, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2030, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2031, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2031, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2031, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2031, 2, 17), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2031, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2031, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2032, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2032, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2032, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2032, 2, 17), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2032, 4, 30), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2032, 5, 2), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2032, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2032, 5, 3), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 3), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2032, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 3), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2033, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2033, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2033, 4, 22), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 24), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2033, 4, 25), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2033, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2033, 5, 3), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2033, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2034, 1, 3), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2034, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2034, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2034, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2034, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2034, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2035, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2035, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2035, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2035, 4, 27), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2035, 4, 29), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2035, 4, 30), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2035, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2035, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2035, 11, 12), "Dan primirja", "Armistice Day Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2036, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2036, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2036, 4, 18), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 20), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2036, 4, 21), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2036, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2036, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2037, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2037, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2037, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2037, 2, 17), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2037, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2037, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2038, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2038, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2038, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2038, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2038, 5, 3), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2038, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 3), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2039, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2039, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2039, 4, 15), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 17), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2039, 4, 18), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2039, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2039, 5, 3), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2039, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Nova Godina", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 1, 2), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2040, 1, 3), "Nova Godina", "New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2040, 1, 7), "Božić", "Orthodox Christmas Day"),
          NationalHoliday.new(Date.new(2040, 2, 15), "Dan državnosti Srbije", "Serbia National Day"),
          NationalHoliday.new(Date.new(2040, 2, 16), "Dan državnosti Srbije", "Serbia National Day Holiday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Praznik rada", "May Day"),
          NationalHoliday.new(Date.new(2040, 5, 2), "Praznik rada", "May Day Holiday"),
          NationalHoliday.new(Date.new(2040, 5, 4), "Veliki petak", "Orthodox Good Friday"),
          NationalHoliday.new(Date.new(2040, 5, 6), "Vaskrs", "Orthodox Easter"),
          NationalHoliday.new(Date.new(2040, 5, 7), "Vaskrsni ponedeljak", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2040, 11, 11), "Dan primirja", "Armistice Day"),
          NationalHoliday.new(Date.new(2040, 11, 12), "Dan primirja", "Armistice Day Holiday")
        ]
      end

    end
  end
end
