module NationalHolidays
  module Countries
    class Slovenia < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Slovenia (all)', 'slovenia01', self.city_municipality_of_ljubljana) ]
      end

      def city_municipality_of_ljubljana
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 1, 2), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2011, 4, 24), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2011, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2011, 6, 12), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2011, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2011, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2011, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2011, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2011, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 1, 2), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2012, 4, 8), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2012, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2012, 5, 27), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2012, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2012, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2012, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2012, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2013, 3, 31), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2013, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2013, 5, 19), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2013, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2013, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2013, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2013, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2014, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2014, 6, 8), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2014, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2014, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2014, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2014, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2015, 4, 5), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2015, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2015, 5, 24), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2015, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2015, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2015, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2015, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2016, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2016, 5, 15), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2016, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2016, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2016, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2016, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2017, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2017, 6, 4), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2017, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2017, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2017, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2017, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2018, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2018, 5, 20), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2018, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2018, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2018, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2018, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2019, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2019, 6, 9), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2019, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2019, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2019, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2019, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2020, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2020, 5, 31), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2020, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2020, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2020, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2020, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2021, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2021, 5, 23), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2021, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2021, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2021, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2021, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2022, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2022, 6, 5), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2022, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2022, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2022, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2022, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2023, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2023, 5, 28), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2023, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2023, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2023, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2023, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2024, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2024, 5, 19), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2024, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2024, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2024, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2024, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2025, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2025, 6, 8), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2025, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2025, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2025, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2025, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2026, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2026, 5, 24), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2026, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2026, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2026, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2026, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2027, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2027, 5, 16), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2027, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2027, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2027, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2027, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2028, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2028, 6, 4), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2028, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2028, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2028, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2028, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2029, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2029, 5, 20), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2029, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2029, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2029, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2029, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2030, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2030, 6, 9), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2030, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2030, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2030, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2030, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2031, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2031, 6, 1), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2031, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2031, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2031, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2031, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2032, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2032, 5, 16), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2032, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2032, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2032, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2032, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2033, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2033, 6, 5), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2033, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2033, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2033, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2033, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2034, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2034, 5, 28), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2034, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2034, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2034, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2034, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2035, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2035, 5, 13), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2035, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2035, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2035, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2035, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2036, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2036, 6, 1), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2036, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2036, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2036, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2036, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2037, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2037, 5, 24), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2037, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2037, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2037, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2037, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2038, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2038, 6, 13), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2038, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2038, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2038, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2038, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2039, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2039, 5, 29), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2039, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2039, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2039, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2039, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Novo leto", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 2, 8), "Prešernov dan, slovenski kulturni praznik", "Prešeren Day, the Slovenian Cultural Holiday"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Velikonočna nedelja", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Velikonočni ponedeljek", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 4, 27), "Dan upora proti okupatorju", "Day of Uprising Against Occupation"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2040, 5, 2), "Praznik dela", "May Day"),
          NationalHoliday.new(Date.new(2040, 5, 20), "Binkoštna nedelja", "Whit Sunday"),
          NationalHoliday.new(Date.new(2040, 6, 25), "Dan državnosti", "Statehood Day"),
          NationalHoliday.new(Date.new(2040, 8, 15), "Marijino vnebovzetje (veliki šmaren)", "Assumption of Mary"),
          NationalHoliday.new(Date.new(2040, 10, 31), "Dan reformacije", "Reformation Day"),
          NationalHoliday.new(Date.new(2040, 11, 1), "Dan spomina na mrtve", "All Saints' Day"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Božič", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Dan samostojnosti in enotnosti", "Independence and Unity Day")
        ]
      end

    end
  end
end
