module NationalHolidays
  module Countries
    class Slovakia < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Slovakia (all)', 'slovakia01', self.bratislava) ]
      end

      def bratislava
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2011, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2011, 4, 22), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2011, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2011, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2011, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2011, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2011, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2011, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2011, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2011, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2011, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2012, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2012, 4, 6), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2012, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2012, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2012, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2012, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2012, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2012, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2012, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2012, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2013, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2013, 3, 29), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2013, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2013, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2013, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2013, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2013, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2013, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2013, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2013, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2014, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2014, 4, 18), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2014, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2014, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2014, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2014, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2014, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2014, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2014, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2014, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2015, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2015, 4, 3), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2015, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2015, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2015, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2015, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2015, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2015, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2015, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2015, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2016, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2016, 3, 25), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2016, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2016, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2016, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2016, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2016, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2016, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2016, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2016, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2017, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2017, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2017, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2017, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2017, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2017, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2017, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2017, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2017, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2018, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2018, 3, 30), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2018, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2018, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2018, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2018, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2018, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2018, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2018, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2018, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2019, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2019, 4, 19), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2019, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2019, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2019, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2019, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2019, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2019, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2019, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2019, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2020, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2020, 4, 10), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2020, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2020, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2020, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2020, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2020, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2020, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2020, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2020, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2021, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2021, 4, 2), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2021, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2021, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2021, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2021, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2021, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2021, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2021, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2021, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2022, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2022, 4, 15), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2022, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2022, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2022, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2022, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2022, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2022, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2022, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2022, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2023, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2023, 4, 7), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2023, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2023, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2023, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2023, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2023, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2023, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2023, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2023, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2024, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2024, 3, 29), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2024, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2024, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2024, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2024, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2024, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2024, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2024, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2024, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2025, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2025, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2025, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2025, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2025, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2025, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2025, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2025, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2025, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2026, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2026, 4, 3), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2026, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2026, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2026, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2026, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2026, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2026, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2026, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2026, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2027, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2027, 3, 26), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2027, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2027, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2027, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2027, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2027, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2027, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2027, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2027, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2028, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2028, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2028, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2028, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2028, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2028, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2028, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2028, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2028, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2029, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2029, 3, 30), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2029, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2029, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2029, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2029, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2029, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2029, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2029, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2029, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2030, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2030, 4, 19), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2030, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2030, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2030, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2030, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2030, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2030, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2030, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2030, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2031, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2031, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2031, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2031, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2031, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2031, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2031, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2031, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2031, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2032, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2032, 3, 26), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2032, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2032, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2032, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2032, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2032, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2032, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2032, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2032, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2033, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2033, 4, 15), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2033, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2033, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2033, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2033, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2033, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2033, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2033, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2033, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2034, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2034, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2034, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2034, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2034, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2034, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2034, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2034, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2034, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2035, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2035, 3, 23), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2035, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2035, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2035, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2035, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2035, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2035, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2035, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2035, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2036, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2036, 4, 11), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2036, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2036, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2036, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2036, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2036, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2036, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2036, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2036, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2037, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2037, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2037, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2037, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2037, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2037, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2037, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2037, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2037, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2038, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2038, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2038, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2038, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2038, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2038, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2038, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2038, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2038, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2039, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2039, 4, 8), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2039, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2039, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2039, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2039, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2039, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2039, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2039, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2039, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Deň vzniku Slovenskej republiky", "Day of the Establishment of the Slovak Republic"),
          NationalHoliday.new(Date.new(2040, 1, 6), "Zjavenie Pána (Traja králi a vianočný sviatok pravoslávnych kresťanov)", "Epiphany (The Three Magi and Christmas Day of Orthododox Christians)"),
          NationalHoliday.new(Date.new(2040, 3, 30), "Veľký piatok", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Veľkonočný pondelok", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Sviatok práce", "International Workers' Day"),
          NationalHoliday.new(Date.new(2040, 5, 8), "Deň víťazstva nad fašizmom", "Day of Victory over Fascism"),
          NationalHoliday.new(Date.new(2040, 7, 5), "Sviatok svätého Cyrila a svätého Metoda", "St. Cyril and Methodius Day"),
          NationalHoliday.new(Date.new(2040, 8, 29), "Výročie Slovenského národného povstania", "Slovak National Uprising Anniversary"),
          NationalHoliday.new(Date.new(2040, 9, 1), "Deň Ústavy Slovenskej republiky", "Day of the Constitution of the Slovak Republic"),
          NationalHoliday.new(Date.new(2040, 9, 15), "Sedembolestná Panna Mária", "Day of Blessed Virgin Mary, Patron Saint of Slovakia"),
          NationalHoliday.new(Date.new(2040, 11, 1), "Sviatok všetkých svätých", "All Saints’ Day"),
          NationalHoliday.new(Date.new(2040, 11, 17), "Deň boja za slobodu a demokraciu", "Struggle for Freedom and Democracy Day"),
          NationalHoliday.new(Date.new(2040, 12, 24), "Štedrý deň", "Christmas Eve"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Prvý sviatok vianočný", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Druhý sviatok vianočný", "St. Stephen's Day")
        ]
      end

    end
  end
end
