module NationalHolidays
  module Countries
    class SouthAfrica < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('South Africa (all)', 'south_africa01', self.gauteng) ]
      end

      def gauteng
        [
          NationalHoliday.new(Date.new(2013, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2013, 3, 29), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2013, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2013, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2013, 6, 17), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2013, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2013, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2013, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2014, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2014, 4, 18), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2014, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2014, 4, 28), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2014, 5, 7), "Election Day", "Election Day"),
          NationalHoliday.new(Date.new(2014, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2014, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2014, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2014, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2015, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2015, 4, 3), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2015, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2015, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2015, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2015, 8, 10), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2015, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2015, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2016, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2016, 3, 25), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2016, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2016, 5, 2), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2016, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2016, 8, 3), "Local Government Election Day", "Local Government Election Day"),
          NationalHoliday.new(Date.new(2016, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2016, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2016, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2016, 12, 27), "Additional Christmas Holiday", "Additional Christmas Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 2), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2017, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2017, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2017, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2017, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2017, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2017, 9, 25), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2017, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2018, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2018, 3, 30), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2018, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2018, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2018, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2018, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2018, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2018, 12, 17), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2019, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2019, 4, 19), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2019, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2019, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2019, 6, 17), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2019, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2019, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2019, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2020, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2020, 4, 10), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2020, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2020, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2020, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2020, 8, 10), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2020, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2020, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2021, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2021, 3, 22), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2021, 4, 2), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2021, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2021, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2021, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2021, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2021, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2021, 12, 27), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2022, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2022, 4, 15), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2022, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2022, 5, 2), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2022, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2022, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2022, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2022, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2023, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 2), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2023, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2023, 4, 7), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2023, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2023, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2023, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2023, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2023, 9, 25), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2023, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2024, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2024, 3, 29), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2024, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2024, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2024, 6, 17), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2024, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2024, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2024, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2025, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2025, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2025, 4, 28), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2025, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2025, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2025, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2025, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2026, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2026, 4, 3), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2026, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2026, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2026, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2026, 8, 10), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2026, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2026, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2027, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2027, 3, 22), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2027, 3, 26), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2027, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2027, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2027, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2027, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2027, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2027, 12, 27), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2028, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2028, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2028, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2028, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2028, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2028, 9, 25), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2028, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2029, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2029, 3, 30), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2029, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2029, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2029, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2029, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2029, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2029, 12, 17), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2030, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2030, 4, 19), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2030, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2030, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2030, 6, 17), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2030, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2030, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2030, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2031, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2031, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2031, 4, 28), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2031, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2031, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2031, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2031, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2032, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2032, 3, 22), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2032, 3, 26), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2032, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2032, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2032, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2032, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2032, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2032, 12, 27), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2033, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2033, 4, 15), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2033, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2033, 5, 2), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2033, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2033, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2033, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2033, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2034, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 2), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2034, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2034, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2034, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2034, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2034, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2034, 9, 25), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2034, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2035, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2035, 3, 23), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2035, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2035, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2035, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2035, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2035, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2035, 12, 17), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2036, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2036, 4, 11), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2036, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2036, 4, 28), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2036, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2036, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2036, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2036, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2037, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2037, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2037, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2037, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2037, 8, 10), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2037, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2037, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2038, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2038, 3, 22), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2038, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2038, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2038, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2038, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2038, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2038, 12, 27), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2039, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2039, 4, 8), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2039, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2039, 5, 2), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2039, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2039, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2039, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2039, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Day of Goodwill", "Day of Goodwill"),
          NationalHoliday.new(Date.new(2040, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 1, 2), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2040, 3, 21), "Human Rights Day", "Human Rights Day"),
          NationalHoliday.new(Date.new(2040, 3, 30), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Family Day", "Family Day"),
          NationalHoliday.new(Date.new(2040, 4, 27), "Freedom Day", "Freedom Day"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Workers' Day", "Workers' Day"),
          NationalHoliday.new(Date.new(2040, 6, 16), "Youth Day", "Youth Day"),
          NationalHoliday.new(Date.new(2040, 8, 9), "National Women's Day", "National Women's Day"),
          NationalHoliday.new(Date.new(2040, 9, 24), "Heritage Day", "Heritage Day"),
          NationalHoliday.new(Date.new(2040, 12, 16), "Day of Reconciliation", "Day of Reconciliation"),
          NationalHoliday.new(Date.new(2040, 12, 17), "Public holiday", "Public holiday"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Day of Goodwill", "Day of Goodwill")
        ]
      end

    end
  end
end
