module NationalHolidays
  module Countries
    class SouthKorea < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('South Korea (all)', 'south_korea01', self.seoul_national_capital_area) ]
      end

      def seoul_national_capital_area
        [
          NationalHoliday.new(Date.new(2013, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 2, 9), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2013, 2, 10), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2013, 2, 11), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2013, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2013, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2013, 5, 17), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2013, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2013, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2013, 9, 18), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2013, 9, 19), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2013, 9, 20), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2013, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2013, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2013, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 1, 30), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2014, 1, 31), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2014, 2, 1), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2014, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2014, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2014, 5, 6), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2014, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2014, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2014, 9, 7), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2014, 9, 8), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2014, 9, 9), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2014, 9, 10), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2014, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2014, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2014, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 2, 18), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2015, 2, 19), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2015, 2, 20), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2015, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2015, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2015, 5, 25), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2015, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2015, 8, 14), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2015, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2015, 9, 26), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2015, 9, 27), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2015, 9, 28), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2015, 9, 29), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2015, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2015, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2015, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 2, 7), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2016, 2, 8), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2016, 2, 9), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2016, 2, 10), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2016, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2016, 4, 13), "대한민국 제20대 국회의원 선거", "National Assembly Election Day"),
          NationalHoliday.new(Date.new(2016, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2016, 5, 14), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2016, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2016, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2016, 9, 14), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2016, 9, 15), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2016, 9, 16), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2016, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2016, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2016, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 27), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2017, 1, 28), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 30), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2017, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2017, 5, 3), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2017, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2017, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2017, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2017, 10, 3), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2017, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2017, 10, 4), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2017, 10, 5), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2017, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2017, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 2, 15), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2018, 2, 16), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2018, 2, 17), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2018, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2018, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2018, 5, 22), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2018, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2018, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2018, 9, 23), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2018, 9, 24), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2018, 9, 25), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2018, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2018, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2018, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 2, 4), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2019, 2, 5), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2019, 2, 6), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2019, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2019, 5, 6), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2019, 5, 12), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2019, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2019, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2019, 9, 12), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2019, 9, 13), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2019, 9, 14), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2019, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2019, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2019, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 24), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2020, 1, 25), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 27), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2020, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2020, 4, 30), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2020, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2020, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2020, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2020, 9, 30), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2020, 10, 1), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2020, 10, 2), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2020, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2020, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2020, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 2, 11), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2021, 2, 12), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2021, 2, 13), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2021, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2021, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2021, 5, 19), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2021, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2021, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2021, 9, 20), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2021, 9, 21), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2021, 9, 22), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2021, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2021, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2021, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 31), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2022, 2, 1), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2022, 2, 2), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2022, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2022, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2022, 5, 8), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2022, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2022, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2022, 9, 9), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2022, 9, 10), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2022, 9, 12), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2022, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2022, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2022, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 21), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2023, 1, 22), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 23), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2023, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2023, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2023, 5, 26), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2023, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2023, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2023, 9, 28), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2023, 9, 29), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2023, 9, 30), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2023, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2023, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2023, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 2, 9), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2024, 2, 10), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2024, 2, 12), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2024, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2024, 5, 6), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2024, 5, 15), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2024, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2024, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2024, 9, 16), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2024, 9, 17), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2024, 9, 18), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2024, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2024, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2024, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 28), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2025, 1, 29), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 30), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2025, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2025, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2025, 5, 5), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2025, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2025, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2025, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2025, 10, 5), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2025, 10, 6), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2025, 10, 7), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2025, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2025, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 2, 16), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2026, 2, 17), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2026, 2, 18), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2026, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2026, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2026, 5, 24), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2026, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2026, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2026, 9, 24), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2026, 9, 25), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2026, 9, 26), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2026, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2026, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2026, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 2, 5), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2027, 2, 6), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2027, 2, 8), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2027, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2027, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2027, 5, 13), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2027, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2027, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2027, 9, 14), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2027, 9, 15), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2027, 9, 16), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2027, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2027, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2027, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 25), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2028, 1, 26), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 27), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2028, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2028, 5, 2), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2028, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2028, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2028, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2028, 10, 2), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2028, 10, 3), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2028, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2028, 10, 4), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2028, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2028, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 2, 12), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2029, 2, 13), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2029, 2, 14), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2029, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2029, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2029, 5, 20), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2029, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2029, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2029, 9, 21), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2029, 9, 22), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2029, 9, 24), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2029, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2029, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2029, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 2, 2), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2030, 2, 3), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2030, 2, 4), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2030, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2030, 5, 6), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2030, 5, 9), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2030, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2030, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2030, 9, 11), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2030, 9, 12), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2030, 9, 13), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2030, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2030, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2030, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 22), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2031, 1, 23), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 24), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2031, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2031, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2031, 5, 28), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2031, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2031, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2031, 9, 30), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2031, 10, 1), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2031, 10, 2), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2031, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2031, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2031, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 2, 10), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2032, 2, 11), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2032, 2, 12), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2032, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2032, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2032, 5, 16), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2032, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2032, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2032, 9, 18), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2032, 9, 19), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2032, 9, 20), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2032, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2032, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2032, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 30), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2033, 1, 31), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2033, 2, 1), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2033, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2033, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2033, 5, 6), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2033, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2033, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2033, 9, 7), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2033, 9, 8), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2033, 9, 9), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2033, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2033, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2033, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 2, 18), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2034, 2, 19), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2034, 2, 20), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2034, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2034, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2034, 5, 25), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2034, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2034, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2034, 9, 26), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2034, 9, 27), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2034, 9, 28), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2034, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2034, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2034, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 2, 7), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2035, 2, 8), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2035, 2, 9), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2035, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2035, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2035, 5, 15), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2035, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2035, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2035, 9, 15), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2035, 9, 16), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2035, 9, 17), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2035, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2035, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2035, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 27), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2036, 1, 28), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 29), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2036, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2036, 5, 3), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2036, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2036, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2036, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2036, 10, 3), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2036, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2036, 10, 4), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2036, 10, 6), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2036, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2036, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 2, 14), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2037, 2, 15), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2037, 2, 16), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2037, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2037, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2037, 5, 22), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2037, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2037, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2037, 9, 23), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2037, 9, 24), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2037, 9, 25), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2037, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2037, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2037, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 2, 3), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2038, 2, 4), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2038, 2, 5), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2038, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2038, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2038, 5, 11), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2038, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2038, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2038, 9, 12), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2038, 9, 13), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2038, 9, 14), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2038, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2038, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2038, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 23), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2039, 1, 24), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 25), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2039, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2039, 4, 30), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2039, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2039, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2039, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2039, 10, 1), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2039, 10, 2), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2039, 10, 3), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2039, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2039, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2039, 12, 25), "성탄절 Seongtanjeol", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 1, 1), "신정 Sinjeong", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 2, 11), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2040, 2, 12), "설날 Seollal", "Korean New Year's Day"),
          NationalHoliday.new(Date.new(2040, 2, 13), "설날 Seollal", "Korean New Year's Day Holiday"),
          NationalHoliday.new(Date.new(2040, 3, 1), "삼일절 Samiljeol", "Independence Movement day"),
          NationalHoliday.new(Date.new(2040, 5, 5), "어린이날 Eorininal", "Children's Day"),
          NationalHoliday.new(Date.new(2040, 5, 18), "석가탄신일 Seokgatansinil", "Buddha's Birthday"),
          NationalHoliday.new(Date.new(2040, 6, 6), "현충일 Hyeonchung-il", "Memorial Day"),
          NationalHoliday.new(Date.new(2040, 8, 15), "광복절 Gwangbokjeol", "Liberation Day"),
          NationalHoliday.new(Date.new(2040, 9, 19), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2040, 9, 20), "추석 Chuseok", "Midautumn Festival"),
          NationalHoliday.new(Date.new(2040, 9, 21), "추석 Chuseok", "Midautumn Festival Holiday"),
          NationalHoliday.new(Date.new(2040, 10, 3), "개천절 Gaecheonjeol", "National Foundation Day"),
          NationalHoliday.new(Date.new(2040, 10, 9), "한글날 Hangeulnal", "Hangul Day"),
          NationalHoliday.new(Date.new(2040, 12, 25), "성탄절 Seongtanjeol", "Christmas Day")
        ]
      end

    end
  end
end
