module NationalHolidays
  module Countries
    class Sweden < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Sweden (all)', 'sweden01', self.stockholm_county) ]
      end

      def stockholm_county
        [
          NationalHoliday.new(Date.new(2011, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2011, 4, 22), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2011, 4, 24), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2011, 6, 2), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2011, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2011, 6, 12), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2011, 6, 24), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2011, 6, 25), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2011, 11, 5), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2011, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2011, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2011, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2012, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2012, 4, 6), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2012, 4, 8), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2012, 5, 17), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2012, 5, 27), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2012, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2012, 6, 22), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2012, 6, 23), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2012, 11, 3), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2012, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2012, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2013, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2013, 3, 29), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2013, 3, 31), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2013, 5, 9), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2013, 5, 19), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2013, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2013, 6, 21), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2013, 6, 22), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2013, 11, 2), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2013, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2013, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2014, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2014, 4, 18), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2014, 4, 20), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2014, 5, 29), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2014, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2014, 6, 8), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2014, 6, 20), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2014, 6, 21), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2014, 11, 1), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2014, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2014, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2015, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2015, 4, 3), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2015, 4, 5), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2015, 5, 14), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2015, 5, 24), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2015, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2015, 6, 19), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2015, 6, 20), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2015, 10, 31), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2015, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2015, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2016, 3, 25), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 27), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2016, 5, 5), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2016, 5, 15), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2016, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2016, 6, 24), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2016, 6, 25), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2016, 11, 5), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2016, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2016, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2016, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2017, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2017, 5, 25), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2017, 6, 4), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2017, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2017, 6, 23), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2017, 6, 24), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2017, 11, 4), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2017, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2017, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2018, 3, 30), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 1), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2018, 5, 10), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2018, 5, 20), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2018, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2018, 6, 22), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2018, 6, 23), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2018, 11, 3), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2018, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2018, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2019, 4, 19), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 21), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2019, 5, 30), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2019, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2019, 6, 9), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2019, 6, 21), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2019, 6, 22), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2019, 11, 2), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2019, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2019, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2020, 4, 10), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 12), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2020, 5, 21), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2020, 5, 31), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2020, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2020, 6, 19), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2020, 6, 20), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2020, 10, 31), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2020, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2020, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2021, 4, 2), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 4), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2021, 5, 13), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2021, 5, 23), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2021, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2021, 6, 25), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2021, 6, 26), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2021, 11, 6), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2021, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2021, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2021, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2021, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2022, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2022, 4, 15), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 17), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2022, 5, 26), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2022, 6, 5), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2022, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2022, 6, 24), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2022, 6, 25), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2022, 11, 5), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2022, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2022, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2022, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2023, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2023, 4, 7), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 9), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2023, 5, 18), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2023, 5, 28), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2023, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2023, 6, 23), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2023, 6, 24), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2023, 11, 4), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2023, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2023, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2024, 3, 29), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 3, 31), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2024, 5, 9), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2024, 5, 19), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2024, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2024, 6, 21), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2024, 6, 22), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2024, 11, 2), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2024, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2024, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2025, 5, 29), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2025, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2025, 6, 8), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2025, 6, 20), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2025, 6, 21), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2025, 11, 1), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2025, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2025, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2026, 4, 3), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 5), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2026, 5, 14), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2026, 5, 24), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2026, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2026, 6, 19), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2026, 6, 20), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2026, 10, 31), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2026, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2026, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2027, 3, 26), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 28), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2027, 5, 6), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2027, 5, 16), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2027, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2027, 6, 25), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2027, 6, 26), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2027, 11, 6), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2027, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2027, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2027, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2027, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2028, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2028, 5, 25), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2028, 6, 4), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2028, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2028, 6, 23), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2028, 6, 24), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2028, 11, 4), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2028, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2028, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2029, 3, 30), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 1), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2029, 5, 10), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2029, 5, 20), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2029, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2029, 6, 22), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2029, 6, 23), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2029, 11, 3), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2029, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2029, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2030, 4, 19), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 21), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2030, 5, 30), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2030, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2030, 6, 9), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2030, 6, 21), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2030, 6, 22), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2030, 11, 2), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2030, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2030, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2031, 5, 22), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2031, 6, 1), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2031, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2031, 6, 20), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2031, 6, 21), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2031, 11, 1), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2031, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2031, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2032, 3, 26), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 28), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2032, 5, 6), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2032, 5, 16), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2032, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2032, 6, 25), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2032, 6, 26), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2032, 11, 6), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2032, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2032, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2032, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2032, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2033, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2033, 4, 15), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 17), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2033, 5, 26), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2033, 6, 5), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2033, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2033, 6, 24), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2033, 6, 25), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2033, 11, 5), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2033, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2033, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2033, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2034, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2034, 5, 18), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2034, 5, 28), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2034, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2034, 6, 23), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2034, 6, 24), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2034, 11, 4), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2034, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2034, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2035, 3, 23), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 25), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2035, 5, 3), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2035, 5, 13), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2035, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2035, 6, 22), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2035, 6, 23), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2035, 11, 3), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2035, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2035, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2036, 4, 11), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 13), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2036, 5, 22), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2036, 6, 1), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2036, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2036, 6, 20), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2036, 6, 21), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2036, 11, 1), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2036, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2036, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2037, 5, 14), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2037, 5, 24), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2037, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2037, 6, 19), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2037, 6, 20), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2037, 10, 31), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2037, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2037, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2038, 6, 3), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2038, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2038, 6, 13), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2038, 6, 25), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2038, 6, 26), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2038, 11, 6), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2038, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2038, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2038, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2038, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2039, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2039, 4, 8), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 10), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2039, 5, 19), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2039, 5, 29), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2039, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2039, 6, 24), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2039, 6, 25), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2039, 11, 5), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2039, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2039, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2039, 12, 31), "Nyårsafton", "New Year's Eve"),
          NationalHoliday.new(Date.new(2040, 1, 1), "Nyårsdagen", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 1, 6), "Trettondagen", "Epiphany"),
          NationalHoliday.new(Date.new(2040, 3, 30), "Långfredagen", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 1), "Påskdagen", "Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Annandag påsk", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 1), "Första maj", "May Day"),
          NationalHoliday.new(Date.new(2040, 5, 10), "Kristi himmelfärds dag", "Ascension Day"),
          NationalHoliday.new(Date.new(2040, 5, 20), "Pingstdagen", "Whit Sunday"),
          NationalHoliday.new(Date.new(2040, 6, 6), "Sveriges nationaldag", "National Day of Sweden"),
          NationalHoliday.new(Date.new(2040, 6, 22), "Midsommarafton", "Midsummer Eve"),
          NationalHoliday.new(Date.new(2040, 6, 23), "Midsommardagen", "Midsummer Day"),
          NationalHoliday.new(Date.new(2040, 11, 3), "Alla helgons dag", "All Saints' Day"),
          NationalHoliday.new(Date.new(2040, 12, 24), "Julafton", "Christmas Eve"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Juldagen", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Annandag jul", "St Stephen's Day"),
          NationalHoliday.new(Date.new(2040, 12, 31), "Nyårsafton", "New Year's Eve")
        ]
      end

    end
  end
end
