module NationalHolidays
  module Countries
    class Ukraine < Country

      def default
        self.regions.first
      end

      def initialize
        @regions = [ Region.new('Ukraine (all)', 'ukraine01', self.kiev_city_municipality) ]
      end

      def kiev_city_municipality
        [
          NationalHoliday.new(Date.new(2015, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 2), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2015, 1, 8), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2015, 1, 9), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2015, 3, 9), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2015, 4, 12), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2015, 4, 13), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2015, 5, 4), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2015, 5, 11), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2015, 5, 31), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2015, 6, 1), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2015, 6, 29), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2015, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2015, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2016, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2016, 5, 1), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2016, 5, 2), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2016, 5, 3), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2016, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2016, 6, 19), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2016, 6, 20), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2016, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2016, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2016, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2017, 1, 2), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 9), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2017, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2017, 4, 16), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2017, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2017, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2017, 6, 4), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2017, 6, 5), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2017, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2017, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2017, 10, 16), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 1, 8), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2018, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2018, 4, 8), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2018, 4, 9), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2018, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2018, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2018, 5, 27), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2018, 5, 28), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2018, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2018, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2018, 10, 15), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2019, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2019, 4, 28), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2019, 4, 29), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2019, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2019, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2019, 6, 16), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2019, 6, 17), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2019, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2019, 8, 26), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2019, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2020, 3, 9), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2020, 4, 19), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2020, 4, 20), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2020, 5, 4), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2020, 5, 11), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2020, 6, 7), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2020, 6, 8), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2020, 6, 29), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2020, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2020, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2021, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2021, 5, 2), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2021, 5, 3), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 3), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2021, 5, 4), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2021, 5, 10), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2021, 6, 20), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2021, 6, 21), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2021, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2021, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2021, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2022, 1, 3), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2022, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2022, 4, 24), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2022, 4, 25), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2022, 5, 3), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2022, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2022, 6, 12), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2022, 6, 13), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2022, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2022, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2022, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2023, 1, 2), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 9), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2023, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2023, 4, 16), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2023, 4, 17), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2023, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2023, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2023, 6, 4), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2023, 6, 5), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2023, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2023, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2023, 10, 16), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 1, 8), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2024, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2024, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2024, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2024, 5, 5), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2024, 5, 6), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2024, 6, 23), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2024, 6, 24), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2024, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2024, 8, 26), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2024, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2025, 3, 10), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2025, 4, 20), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2025, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2025, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2025, 6, 8), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2025, 6, 9), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2025, 6, 30), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2025, 8, 25), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2025, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2026, 3, 9), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2026, 4, 12), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2026, 4, 13), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2026, 5, 4), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2026, 5, 11), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2026, 5, 31), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2026, 6, 1), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2026, 6, 29), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2026, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2026, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2027, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2027, 5, 2), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2027, 5, 3), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 3), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2027, 5, 4), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2027, 5, 10), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2027, 6, 20), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2027, 6, 21), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2027, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2027, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2027, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2028, 1, 3), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2028, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2028, 4, 16), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2028, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2028, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2028, 6, 4), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2028, 6, 5), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2028, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2028, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2028, 10, 16), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 1, 8), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2029, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2029, 4, 8), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2029, 4, 9), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2029, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2029, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2029, 5, 27), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2029, 5, 28), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2029, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2029, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2029, 10, 15), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2030, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2030, 4, 28), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2030, 4, 29), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2030, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2030, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2030, 6, 16), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2030, 6, 17), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2030, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2030, 8, 26), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2030, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2031, 3, 10), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2031, 4, 13), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2031, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2031, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2031, 6, 1), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2031, 6, 2), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2031, 6, 30), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2031, 8, 25), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2031, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2032, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2032, 5, 2), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2032, 5, 3), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 3), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2032, 5, 4), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2032, 5, 10), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2032, 6, 20), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2032, 6, 21), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2032, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2032, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2032, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2033, 1, 3), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2033, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2033, 4, 24), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2033, 4, 25), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2033, 5, 3), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2033, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2033, 6, 12), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2033, 6, 13), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2033, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2033, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2033, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2034, 1, 2), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 9), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2034, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2034, 4, 9), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2034, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2034, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2034, 5, 28), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2034, 5, 29), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2034, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2034, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2034, 10, 16), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 1, 8), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2035, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2035, 4, 29), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2035, 4, 30), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2035, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2035, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2035, 6, 17), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2035, 6, 18), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2035, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2035, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2035, 10, 15), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2036, 3, 10), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2036, 4, 20), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2036, 4, 21), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2036, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2036, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2036, 6, 8), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2036, 6, 9), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2036, 6, 30), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2036, 8, 25), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2036, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2037, 3, 9), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2037, 4, 5), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2037, 5, 4), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2037, 5, 11), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2037, 5, 24), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2037, 5, 25), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2037, 6, 29), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2037, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2037, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2038, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2038, 4, 25), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 3), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2038, 5, 4), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2038, 5, 10), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2038, 6, 13), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2038, 6, 14), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2038, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2038, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2038, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2039, 1, 3), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 1, 7), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2039, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2039, 4, 17), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2039, 4, 18), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2039, 5, 3), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2039, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2039, 6, 5), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2039, 6, 6), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2039, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2039, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2039, 10, 14), "День захисника України", "Defender of Ukraine Day"),
          NationalHoliday.new(Date.new(2040, 1, 2), "Новий Рік", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 1, 9), "Різдво", "Orthodox Christmas"),
          NationalHoliday.new(Date.new(2040, 3, 8), "Міжнародний жіночий день", "International Women's Day"),
          NationalHoliday.new(Date.new(2040, 5, 1), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2040, 5, 2), "День праці (День міжнародної солідарності трудящих)", "Labor Day"),
          NationalHoliday.new(Date.new(2040, 5, 6), "Пасха", "Orthodox Easter Sunday"),
          NationalHoliday.new(Date.new(2040, 5, 7), "Пасха", "Orthodox Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 9), "День перемоги над нацизмом у Другій світовій війні", "Victory Day"),
          NationalHoliday.new(Date.new(2040, 6, 24), "Трійця", "Orthodox Whit Sunday"),
          NationalHoliday.new(Date.new(2040, 6, 25), "Трійця", "Orthodox Whit Monday"),
          NationalHoliday.new(Date.new(2040, 6, 28), "День Конституції", "Constitution Day"),
          NationalHoliday.new(Date.new(2040, 8, 24), "День Незалежності", "Independence Day"),
          NationalHoliday.new(Date.new(2040, 10, 15), "День захисника України", "Defender of Ukraine Day")
        ]
      end

    end
  end
end
