module NationalHolidays
  module Countries
    class UnitedKingdom < CountryNationalHolidays

      attr_reader :england, :wales, :scotland, :northern_ireland

      def default
        self.england
      end

      def initialize
        @regions = [ 'England', 'Wales', 'Scotland', 'Northern Ireland' ]

        @england = [
          NationalHoliday.new(Date.new(2011, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 4, 22), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 4, 29), "Royal Wedding Day", "Royal Wedding Day"),
          NationalHoliday.new(Date.new(2011, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2011, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 4, 6), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 6, 4), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 6, 5), "Queen's Diamond Jubilee", "Queen's Diamond Jubilee"),
          NationalHoliday.new(Date.new(2012, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 3, 29), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 4, 18), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 8, 25), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 4, 3), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 8, 31), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 28), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 3, 25), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2016, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 3, 30), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 4, 19), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 4, 10), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 8, 31), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 28), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 4, 2), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 8, 30), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2021, 12, 28), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 4, 15), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2022, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 4, 7), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 3, 29), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 8, 25), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 4, 3), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 8, 31), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 28), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 3, 26), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2027, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2027, 8, 30), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2027, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2027, 12, 28), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 3, 30), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 4, 19), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2031, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2031, 8, 25), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 3, 26), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 8, 30), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2032, 12, 28), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 4, 15), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2033, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 3, 23), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2035, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2035, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 4, 11), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2036, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2036, 8, 25), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2037, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2037, 8, 31), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 28), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2038, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2038, 8, 30), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2038, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2038, 12, 28), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 4, 8), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2039, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2039, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2039, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 3, 30), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2040, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2040, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Boxing Day", "Boxing Day")
        ]

        @wales = [
          NationalHoliday.new(Date.new(2011, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 4, 22), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 4, 29), "Royal Wedding Day", "Royal Wedding Day"),
          NationalHoliday.new(Date.new(2011, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2011, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 4, 6), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 6, 4), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 6, 5), "Queen's Diamond Jubilee", "Queen's Diamond Jubilee"),
          NationalHoliday.new(Date.new(2012, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 3, 29), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 4, 18), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 8, 25), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 4, 3), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 8, 31), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 28), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 3, 25), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2016, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 4, 14), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 3, 30), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 4, 19), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 4, 10), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 8, 31), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 28), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 4, 2), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 8, 30), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2021, 12, 28), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 4, 15), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2022, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 4, 7), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 3, 29), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 8, 25), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 4, 3), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 8, 31), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 28), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 3, 26), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2027, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2027, 8, 30), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2027, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2027, 12, 28), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 4, 14), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 3, 30), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 4, 19), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2031, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2031, 8, 25), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 3, 26), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 8, 30), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2032, 12, 28), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 4, 15), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2033, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 4, 7), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2035, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2035, 3, 23), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2035, 3, 26), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2035, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2035, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2035, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2035, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2035, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2036, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2036, 4, 11), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2036, 4, 14), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2036, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2036, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2036, 8, 25), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2036, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2036, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2037, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2037, 4, 3), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2037, 4, 6), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2037, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2037, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2037, 8, 31), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2037, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2037, 12, 28), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2038, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2038, 4, 23), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2038, 4, 26), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2038, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2038, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2038, 8, 30), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2038, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2038, 12, 28), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2039, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2039, 4, 8), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2039, 4, 11), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2039, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2039, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2039, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2039, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2039, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2040, 3, 30), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2040, 4, 2), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2040, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2040, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2040, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2040, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2040, 12, 26), "Boxing Day", "Boxing Day")
        ]

        @scotland = [
          NationalHoliday.new(Date.new(2011, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 1, 4), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 4, 29), "Royal Wedding Day", "Royal Wedding Day"),
          NationalHoliday.new(Date.new(2011, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 8, 1), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2011, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 6, 4), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 6, 5), "Queen's Diamond Jubilee", "Queen's Diamond Jubilee"),
          NationalHoliday.new(Date.new(2012, 8, 6), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2013, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 8, 5), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2014, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 8, 4), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2015, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 8, 4), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 28), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2016, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 1, 4), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 8, 1), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2016, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 8, 7), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2018, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 8, 6), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2019, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 8, 5), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2020, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 8, 3), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 28), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2021, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 1, 4), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 8, 2), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2021, 12, 28), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2022, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 1, 4), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 8, 1), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2022, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 8, 7), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2024, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 8, 5), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2025, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 8, 4), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2026, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 8, 3), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 28), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2027, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 1, 4), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2027, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2027, 8, 2), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2027, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2027, 12, 28), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 1, 4), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 8, 7), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2029, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 8, 6), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2030, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 8, 5), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2031, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2031, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2031, 8, 4), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2032, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 8, 2), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2032, 12, 28), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2033, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 1, 4), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 8, 1), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2033, 12, 27), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 8, 7), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Boxing Day", "Boxing Day"),
        ]

        @northern_ireland = [
          NationalHoliday.new(Date.new(2011, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2011, 4, 25), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2011, 4, 29), "Royal Wedding Day", "Royal Wedding Day"),
          NationalHoliday.new(Date.new(2011, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2011, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2011, 12, 27), "Christmas Day", "Christmas Day"),

          NationalHoliday.new(Date.new(2012, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2012, 3, 19), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2012, 4, 9), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2012, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 6, 4), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 6, 5), "Queen's Diamond Jubilee", "Queen's Diamond Jubilee"),
          NationalHoliday.new(Date.new(2012, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2012, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2012, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2012, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2013, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2013, 3, 18), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2013, 4, 1), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2013, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2013, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2013, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2013, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2014, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2014, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2014, 4, 21), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2014, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 6, 14), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2014, 8, 25), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2014, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2014, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2015, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2015, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2015, 4, 6), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2015, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 6, 13), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2015, 8, 31), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2015, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2015, 12, 28), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2016, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2016, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2016, 3, 28), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2016, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2016, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2016, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2016, 12, 27), "Christmas Day", "Christmas Day"),

          NationalHoliday.new(Date.new(2017, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2017, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2017, 4, 17), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2017, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2017, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2017, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2017, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2018, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2018, 3, 19), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2018, 4, 2), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2018, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2018, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2018, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2018, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2019, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2019, 3, 18), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2019, 4, 22), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2019, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2019, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2019, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2019, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2020, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2020, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2020, 4, 13), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2020, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 6, 13), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2020, 8, 31), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2020, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2020, 12, 28), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2021, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2021, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2021, 4, 5), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2021, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2021, 8, 30), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2021, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2021, 12, 28), "Christmas Day", "Christmas Day"),

          NationalHoliday.new(Date.new(2022, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2022, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2022, 4, 18), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2022, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2022, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2022, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2022, 12, 27), "Christmas Day", "Christmas Day"),

          NationalHoliday.new(Date.new(2023, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2023, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2023, 4, 10), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2023, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2023, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2023, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2023, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2024, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2024, 3, 18), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2024, 4, 1), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2024, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2024, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2024, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2024, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2025, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2025, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2025, 4, 18), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2025, 4, 21), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2025, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 6, 14), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2025, 8, 25), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2025, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2025, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2026, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2026, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2026, 4, 6), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2026, 5, 4), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 5, 25), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 6, 13), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2026, 8, 31), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2026, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2026, 12, 28), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2027, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2027, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2027, 3, 29), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2027, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2027, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2027, 8, 30), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2027, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2027, 12, 28), "Christmas Day", "Christmas Day"),

          NationalHoliday.new(Date.new(2028, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2028, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2028, 4, 17), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2028, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2028, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2028, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2028, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2029, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2029, 3, 19), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2029, 4, 2), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2029, 5, 7), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 5, 28), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2029, 8, 27), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2029, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2029, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2030, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2030, 3, 18), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2030, 4, 22), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2030, 5, 6), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 5, 27), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2030, 8, 26), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2030, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2030, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2031, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2011, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2031, 4, 11), "Good Friday", "Good Friday"),
          NationalHoliday.new(Date.new(2031, 4, 14), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2031, 5, 5), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2031, 5, 26), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2011, 6, 14), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2031, 8, 25), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2031, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2031, 12, 26), "Boxing Day", "Boxing Day"),

          NationalHoliday.new(Date.new(2032, 1, 1), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2032, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2032, 3, 29), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2032, 5, 3), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 5, 31), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2032, 8, 30), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2032, 12, 27), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2032, 12, 28), "Christmas Day", "Christmas Day"),

          NationalHoliday.new(Date.new(2033, 1, 3), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2033, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2033, 4, 18), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2033, 5, 2), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 5, 30), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2033, 8, 29), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2033, 12, 26), "Boxing Day", "Boxing Day"),
          NationalHoliday.new(Date.new(2033, 12, 27), "Christmas Day", "Christmas Day"),

          NationalHoliday.new(Date.new(2034, 1, 2), "New Year's Day", "New Year's Day"),
          NationalHoliday.new(Date.new(2034, 3, 17), "St. Patrick's Day", "St. Patrick's Day"),
          NationalHoliday.new(Date.new(2034, 4, 10), "Easter Monday", "Easter Monday"),
          NationalHoliday.new(Date.new(2034, 5, 1), "May Day Bank Holiday", "May Day Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 5, 29), "Spring Bank Holiday", "Spring Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 6, 12), "Battle of the Boyne", "Battle of the Boyne"),
          NationalHoliday.new(Date.new(2034, 8, 28), "Late Summer Bank Holiday", "Late Summer Bank Holiday"),
          NationalHoliday.new(Date.new(2034, 12, 25), "Christmas Day", "Christmas Day"),
          NationalHoliday.new(Date.new(2034, 12, 26), "Boxing Day", "Boxing Day")
        ]
      end
    end
  end
end
